### ISSUE TITLE
Project list > changes... gets MNU 

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#102]
ProjectListBrowser changes... not usable.

RwPrjDiffTool DNU diffForProjectName:, in this method:

	^(Rowan projectTools diff diffForProjectName: name) asString

**Comment by dalehenrich** [comment]
see issue #85, TL;DR it's on Eric's list

**Comment by ericwinger** [comment]
Fixed in Jadeite 0.9.0
