### ISSUE TITLE
Datacurator needs to be functional

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#104]
...

**Comment by LisaAlmarode** [comment]
As DataCurator, I can clone RowanSample2, but when I try to load it I get a SecurityError, "An attempt was made to modify the object aRwGsPlatform in objectSecurityPolicyId 1 with insufficient authorization"

**Comment by dalehenrich** [comment]
... good to know that it does not work ... I was wondering if there were going to be any security issues ... the particuluar error you mention is likely to be a lazy initialization problem ... but I'd have to see a full stack to know for sure ... if you press the 'Copy` button when the initial debug window pops up, you can copy both the exact error and stack ... it is always useful for me to have the error message and full stack, so that if nothing else, I can know that I reproduced the same problem that you saw ... and therefore fix the issue that you are seeing ...

**Comment by dalehenrich** [comment]
- [ ] empty project list

**Comment by dalehenrich** [comment]
Successfully load RowanSample2, made an edit and saved the project ... getting project list and creating the project seemed to be the main trouble points ...

**Comment by dalehenrich** [comment]
There are some issues with running tests as both SystemUser and DataCurator, but for normal single user use case: installing Rowan as SystemUser and doing development as DataCurator, we are good to go ...
