### ISSUE TITLE
Cleanup Project Changes

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#106]
Removed "dkh ..." in Detail.   

Change title to show  Rowan Project changes somehow.

**Comment by ericwinger** [comment]
Added Rowan Project changes. Dale - How hard would it be to remove that dkh timestamp string you put in?   That might be easier than me ripping it out of everywhere that Jade uses it with the MCPatch.

**Comment by dalehenrich** [comment]
It should be easy to rip out, but I am under the impression that Jadeite string parsing will fail if I remove it ... so perhaps we should coordinate tomorrow and make the change to Rowan and Jadeite at the same time ...

**Comment by dalehenrich** [comment]
@ericwinger is this still an item for alpha? It's dropping to the bottom of my list, not because it's hard, but because as soon as I make the change my diffs will break --- this is something we will have to do in the same commit and image together to get it working right ...

**Comment by ericwinger** [comment]
When you do a diffs, the Detail column will often say 'dkh ...'.   I'll reassign to myself and see if I can find an easy way to not display that.
