### ISSUE TITLE
return result of successful method compile

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#11]
In order to update the Dolphin/GS Jade browsers, it would be helpful if the return value of a successful method compile contained this information - method oop, selector. 

In particular, RwPrjBrowserTool>>addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed:?
currently returns a RwProjectSetModification. ​

It's not clear to me how to navigate through that object to return the above information.

**Comment by dalehenrich** [comment]
With the above fix, you will get back an instance of **GsNMethod** from which you can derive both the oop and the selector ... 

Note that I've added the following two methods that might be a bit more convenient to use:
```
  Behavior>>rwCompileMethod:category:
  Behavior>>rwCompileMethod:category:packageName:
```
to go along with these (also possibly more convenient) methods in **Class** added in commit 0d183ac:
```
  Class>>rwByteSubclass:classVars:classInstVars:poolDictionaries:inDictionary:category:options:
  Class>>rwByteSubclass:classVars:classInstVars:poolDictionaries:inDictionary:category:packageName:options:
  Class>>rwIndexableSubclass:instVarNames:classVars:classInstVars:poolDictionaries:inDictionary:category:options:
  Class>>rwIndexableSubclass:instVarNames:classVars:classInstVars:poolDictionaries:inDictionary:category:packageName:options:
  Class>>rwSubclass:instVarNames:classVars:classInstVars:poolDictionaries:inDictionary:category:options:
  Class>>rwSubclass:instVarNames:classVars:classInstVars:poolDictionaries:inDictionary:category:packageName:options:
```
All of these new methods end up calling the `Rowan projectTools browser` API methods
