### ISSUE TITLE
moving methods between method categories does not show as changed

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#111]
- Move a method between categories, but don't change the method in any other way. 
- Show changes on either the project or package. 
- No change is noted. 

I don't believe that Rowan is returning any changes to Jadeite. 

Could you verify this works or does not work in tode?

**Comment by dalehenrich** [comment]
... if you move a method to a different category and write it to disk, does it show up? I don't think I've got any test cases for this, so it is likely to be a real issue ...

**Comment by LisaAlmarode** [comment]
When I move a method to another category and make no other changes, and try to do the Jadeite git commit, I get an error that there was nothing to commit (the same as if I commit a project with no changes).

**Comment by ericwinger** [comment]
When #113  is fixed, I'll retest this.

**Comment by dalehenrich** [comment]
this is now ready for Jadeite integration (seee #116) with the addition of Behavior>>rwMoveMethod:toCategory:
