### ISSUE TITLE
Need Rowan API calls to replace a number of additional Jadeite class related methods

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#116]
Eric found that the following methods are being sent to classes in Jade:
```
_primitiveCompileMethod:symbolList:category:oldLitVars:intoMethodDict: intoCategories:intoPragmas: nil.
_primitiveCompileMethodsymbolList:category:obsoleteClassNames:oldLitVars: 
_primitiveCompileMethodL:symbolList:category:oldLitVars:intoMethodDict:intoCateories:
addCategory:
category:
comment:
compileMissingAccessingMethods
compileAccessingMethodsFor:
compileMethod:dictionaries:category:
compileMethod:behavior:symbolList:inCategory:
changeNameTo:
documentClassWith:
migrateInstances:to:
moveMethod:toCategory:
removeCategory:
removeFromSystem
removeSelector:
removeVersion:
renameCategory:to:
```
Most of not all of the message sends need to be replaced by Rowan api calls ... unless they are in dead code. 

First order of business is to implement equivalent Rowan API calls, then start using them in Jadeite ...

**Comment by dalehenrich** [comment]
keep track of progress as we address each of the methods:
- [ ] _primitiveCompileMethod:symbolList:category:oldLitVars:intoMethodDict: intoCategories:intoPragmas: nil.
- [ ] _primitiveCompileMethodsymbolList:category:obsoleteClassNames:oldLitVars: 
- [ ] _primitiveCompileMethodL:symbolList:category:oldLitVars:intoMethodDict:intoCateories:
- [ ] addCategory:
- [ ] category:
- [ ] comment:
- [ ] compileMissingAccessingMethods
- [ ] compileAccessingMethodsFor:
- [ ] compileMethod:dictionaries:category:
- [ ] compileMethod:behavior:symbolList:inCategory:
- [ ] changeNameTo:
- [ ] documentClassWith:
- [ ] migrateInstances:to:
- [ ] moveMethod:toCategory:
- [ ] removeCategory:
- [ ] removeFromSystem
- [ ] removeSelector:
- [ ] removeVersion:
- [ ] renameCategory:to:

**Comment by ericwinger** [comment]
The three _primitiveCompile* methods are sent by JadeServer>>compileMethod:behavior:symbolList:inCategory: if Behavior canUnderstand: returns true. 

In 3.2.15, canUnderstand: returns false.

**Comment by ericwinger** [comment]
compileMethod:behavior:symbolList:inCategory:  is in fact a JadeServer method. Crossing off list.

**Comment by ericwinger** [comment]
removeFromSystem is a Rowan method, it appears.

**Comment by ericwinger** [comment]
Class>>category: sets the class category of the receiver which, I believe, is not supported in Rowan. 

A monticello feature. Checking off list.

**Comment by ericwinger** [comment]
changeNameTo:

If you select a class twice in the rowan browser, the class becomes editable. Checking off this list, but see #135 for next steps.

**Comment by ericwinger** [comment]
addCategory: & removeCategory: are used, but according to the comments in #28, we may not need rowan apis for category control. Need input from @dalehenrich.

**Comment by ericwinger** [comment]
removeSelector: 

Don't think this is sent by any Jadeite code.

**Comment by dalehenrich** [comment]
We could support `Class>>category:` and for Jadeite it would be more properly name `move class to package` ...

**Comment by dalehenrich** [comment]
Here's the list of methods that I need to implement Rowan api calls for:
- [x] comment: -> rwComment: (#136 )
- [ ] changeNameTo: (issue #135)
- [ ] moveMethod:toCategory:

**Comment by dalehenrich** [comment]
full resolution of #moveMethod:ToCategory: will have to wait on #125, since the RwHybridBrowserToolTest>>testHybridMoveMethod test case hits the unimplemented methods!

**Comment by dalehenrich** [comment]
Calling moveMethod:toCategory: ready to be integrated into Rowan. session method moves are not yet fully functional, but that shouldn't prevent us having the rowanized version of moveMethod:toCategory: integrated into Jadeite.

Bouncing to @ericwinger - bounce back to me after Jadeite has been integrated ... I have failing tests to remind me that this issue isn't complete (testHybridMoveMethodFromSessionMethodsIntoSessionMethods and testHybridMoveMethodIntoSessionMethods):
```
147 run, 141 passed, 3 failed, 3 errors
  errors
	RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
	RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
	RwRowanSample2Test>>#testNoMigration_gitolite
  failures
	RwLoadingTest>>#testPoolDictionaryChanges
	RwSymbolDictionaryTest>>#testClassVersioningPatch
	RwRowanProjectIssuesTest>>#testIssue123_moveExistingClassWithMethodsAndSubclassesToNewPackageAndNewClassVersion
```
will be merging my work into candidate branch so that @ericwinger can integrate into Jadeite

**Comment by dalehenrich** [comment]
Bouncing to @ericwinger for integration into Jadeit

**Comment by ericwinger** [comment]
Reassigning to Dale for verification that this issue can (or cannot) be closed.

**Comment by dalehenrich** [comment]
Let's call this one closed ... I've got failing tests and will open new issues for those ... if neeeded. THX
