### ISSUE TITLE
Uncommitted class version method, can't be found by implementors menu item

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#121]
If you create a version of a class (say, add an instance variable), and add an accessor method, and then try to look at implementors ...  you get nuthin'.  Only once you commit to GemStone does the  implementors menu show a list containing the selected method in the method list.

**Comment by ericwinger** [comment]
I believe that Jadite uses the ClassOrganizer for implementors and senders. If so, the necessity of a commit may be related to that. I've seen similar behavior in GBS but can't recall off the top of my head what the resolution was. Might be a Kermit bug on it somewhere.

**Comment by ericwinger** [comment]
I'll look into it after alpha.
