### ISSUE TITLE
New version of class in new package loses methods already in the new package. 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#123]
- Create class Issue91 in Package RowanSample1-XXX.
- Add extension method category, *rowansample1-extensions, in class Issue91
- Add method extendedMethod in new category. 
- Verify by Show Changes that RowanSample1-Extensions package shows the new method was added.
-  Using the class definition template, create a new version of Issue91 with new  inst var 'abc' in RowanSample1-Extensions
- Verify Issue91 has moved to RowanSample1-Extensions package. 
- Bug is that method extendedMethod was not brought into the new class version. No methods are shown.

**Comment by dalehenrich** [comment]
this looks to be a variant of the issues that I have been addressing with the work on #114 which involved extensive improvement to the new class version logic ...

**Comment by dalehenrich** [comment]
.... this puppy is still misbehaving after recent changes ... will need to fix this one

**Comment by dalehenrich** [comment]
The test `RwRowanProjectIssuesTest>>#testIssue123_moveExistingClassWithMethodsAndSubclassesToNewPackageAndNewClassVersion` is still failing and it should be looked at closely
