### ISSUE TITLE
MNU when creating new project

### ISSUE THREAD

**Issue by nrgiii** [dalehenrich/Rowan#124]
Note the given path clearly *does * exist.

normg@moop>ll /export/moop3/users/normg/rph/RowanSample1/specs/RowanSample1.ston
-rw-r--r-- 1 normg smalltalk 448 Apr 27 09:43 /export/moop3/users/normg/rph/RowanSample1/specs/RowanSample1.ston
/home/normg/local/m3/rph/Rowan/test/testRepositories/repos

![image](https://user-images.githubusercontent.com/4521934/39375067-dc954d1a-4a01-11e8-8373-be0c6125436c.png)

**Comment by dalehenrich** [comment]
Norm, when I used  `file:/export/moop3/users/normg/rph/RowanSample1/specs/RowanSample1.ston` with the `Clone Git Project ...` menu item, I was able to successfully find the .ston file reference ... so perhaps there is something else funky with where your gem is running.

What does `GsFile exists: '/export/moop3/users/normg/rph/RowanSample1/specs/RowanSample1.ston'` return? The error itself is coming when this expression is evaluated: `GsFile openReadOnServer: '/export/moop3/users/normg/rph/RowanSample1/specs/RowanSample1.ston'`

**Comment by dalehenrich** [comment]
I'm running on rogue in the office on the wired network when I run this test ...

**Comment by dalehenrich** [comment]
I think this one is fixed now
