### ISSUE TITLE
Jadeite Alpha 1.0 doesn't allow logins if ROWAN_HOME is not set

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#129]
I changed the installation scripts for Issue #107 and when I went to do a test login, I get the following error:
![image](https://user-images.githubusercontent.com/623951/39402298-ee002110-4b0f-11e8-82a0-c195bf551876.png)
I can finesse this for testing, but this should be changed before the drop and I won't be able to merge my work into the master branch until this is fixed, either.

**Comment by ericwinger** [comment]
I'll change the $ROWAN_HOME check to a $ROWAN_PROJECTS_HOME check.

**Comment by dalehenrich** [comment]
but for Jadeite to work, doesn't this require code that has not been checked into master?
