### ISSUE TITLE
method compilation category restrictions? 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#13]
In order to use the recently-added #rwCompileMethod's on Behavior, is it required to have created the package first?  

(I don't have a way for you to easily reproduce this walkback)

UserDefinedError (AbstractException) >> _signalWith: @6 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwPrjBrowserTool (Object) >> error: @6 line 7
[] in RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @13 line 18
RwGsImage class >> loadedHybridPackageNamed:ifAbsent: @5 line 14
Rowan class >> loadedHybridPackageNamed:ifAbsent: @3 line 3
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @3 line 15
RowanMethodDefinitionService class (Behavior) >> rwCompileMethod:category: @8 line 4
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @12 line 7
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @8 line 13
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @3 line 15
JadeServer64bit34 (JadeServer) >> sbSaveMethod: @13 line 9
JadeServer64bit34 (JadeServer) >> systemBrowserCommand @122 line 40
[] in JadeServer >> systemBrowserA: @23 line 10
Time class >> secondsElapsedTime: @6 line 11
"rowanStack.gs" [dos] 25L, 1585C                              1,1           Top

**Comment by dalehenrich** [comment]
If the error was complaining about a missing package then yes you need to create the package before using the method ... it looks you are using `rwCompileMethod:category: ` so the package name needs a leading $* ... there are potentially several potential errors so the error message in this method, so I'm guessing that it is the missing package error ...

**Comment by ericwinger** [comment]
Duly noted.
