### ISSUE TITLE
class creation template (dictionaries view) does not have category filled in when no class is selected 

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#131]
Note that the category is nil:
![image](https://user-images.githubusercontent.com/623951/39402869-e9a7120c-4b20-11e8-86dd-883b08ab0315.png)
I imagine that Jadeite is passing in the nil category when I would expect it to pass in the name of the package (`RowanSample1-XXX`)

**Comment by ericwinger** [comment]
This is less broken, but still broken in Alpha1.0.1. If --All Categories-- is selected the package looks funny. @dalehenrich @LisaAlmarode
