### ISSUE TITLE
`file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample1.st` should be default spec in `Clone Git Project`

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#132]
I created the `samples` directory this morning (7c45a93) and figure that its a better location than test/specs for example specs ...

No hurry need to add for Alpha

**Comment by dalehenrich** [comment]
we might want to make this change for Alpha

**Comment by ericwinger** [comment]
The prior default pointed to a '.ston' file. Did you want to change it to '.st'? 
Assign to Dale for confirmation.

**Comment by ericwinger** [comment]
Answer from Dale was '.ston' is still correct.
