### ISSUE TITLE
Add package fails, defaultProjectName returns nil

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#139]
Wanted to try adding a package (use the "add package" menu option, in the packages view).  The default package is set (has asterisk), RowanSample1.  and yet, 

RowanProjectService defaultProjectName 
returns nil.

This is the stack:

a ArgumentError occurred (error 2090), reason:rtErrNilKey, An illegal attempt was made to store nil as a key in the dictionary aDictionary( ).

ArgumentError (AbstractException) >> _signalWith: @5 line 25
ArgumentError (AbstractException) >> signal @2 line 47
Dictionary (Object) >> _error: @13 line 7
Dictionary (AbstractDictionary) >> errorNilKey @2 line 5
Dictionary >> at:put: @3 line 9
RwProjectSetDefinition (RwDefinitionSetDefinition) >> addDefinition: @7 line 7
RwPrjLoadTool >> loadProjectDefinition: @4 line 5
RwPrjBrowserTool >> createGitPackageProjectNamed:updateDefinition: @7 line 7
RowanProjectService >> createProjectNamed:in: @7 line 5
RowanProjectService >> createProjectNamed: @3 line 3
RowanPackageService >> createPackage @6 line 5
JadeServer64bit32 (JadeServer) >> sbAddPackage: @7 line 6
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @21 line 9
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Need to ensure a few things happen: 

- [ ] Loading a project sets the default project in both the client & server. 

- [ ] DataCurator can change/set the default project properly. 

- [ ] A nicer error message is given when adding a package but no default project is set.
