### ISSUE TITLE
extension class error 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#15]
Create a package named 'examples' in project 'RowanProject'. 
Committed my gemstone transaction. 
Then I tried to compile a method RowanPackageDefinitionService>>createPackageNamed:inProject:
Got the error below. 

My code sent #rwCompileMethod: <methodString> category: '*examples*' to the behavior. 

UserDefinedError (AbstractException) >> _signalWith: @6 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsPackageSymbolDictionary (Object) >> error: @6 line 7
[] in RwGsPackageSymbolDictionary >> ensureExtensionClassNamed:existsForPackageNamed: @20 line 8
RwGsPackageSymbolDictionary (SymbolDictionary) >> at:ifAbsent: @13 line 18
RwGsPackageSymbolDictionary >> ensureExtensionClassNamed:existsForPackageNamed: @4 line 5
RwGsClassExtensionSymbolDictPatch >> installClassExtensionInSystem @17 line 16
[] in RwGsPatchSetBasic >> installAddedClassExtensions @5 line 3
[] in Set >> do: @8 line 11
KeyValueDictionary >> keysDo: @20 line 18
Set >> do: @4 line 11
RwGsPatchSetBasic >> installAddedClassExtensions @2 line 3
RwGsPatchSetBasic >> apply @15 line 19
RwGsImage class >> applyModification: @11 line 9
RwPrjLoadTool >> loadProjectSetDefinition: @14 line 13
[] in RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @69 line 55
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @24 line 85
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @6 line 23
RowanPackageDefinitionService class (Behavior) >> rwCompileMethod:category: @8 line 4
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @12 line 7
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @8 line 13
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @3 line 15
JadeServer64bit34 (JadeServer) >> sbSaveMethod: @13 line 9
JadeServer64bit34 (JadeServer) >> systemBrowserCommand @122 line 40
[] in JadeServer >> systemBrowserA: @23 line 10
Time class >> secondsElapsedTime: @6 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit34 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserA: @3 line 4
JadeServer64bit34 (JadeServer) >> systemBrowser: @3 line 2
[] in JadeServer64bit >> systemBrowser: @7 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit) >> systemBrowser: @3 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by 69** [comment]
sounds complex, good luck

**Comment by dalehenrich** [comment]
Did you rebuild with the most recent checkout (after I sent you the message about changing how you commit?) also I would like to see the actual error message...

Anyway it seems that you have not created the class you are extending with Rowan or ??? the error message would help me give you better advice

**Comment by ericwinger** [comment]
No, I didn't rebuild but will now. 

The class already existed in Rowan>Services category. I was trying to add a new method to it using the '*protocol' naming technique we discussed yesterday.

**Comment by dalehenrich** [comment]
What was the error message?

**Comment by ericwinger** [comment]
I don't have the error message now. After rebuild, I see a different error which is a little more helpful. 

I'll setup the api's to create a class in Rowan then I'll retry this code. 

a UserDefinedError occurred (error 2318), reason:halt, loaded class named 'RowanPackageDefinitionService' not

**Comment by dalehenrich** [comment]
Okay ... RowanPackageDefinitionService is not registered as a loaded class, because we aren't quite using Rowan for managing Rowan ... yet ... I won't flip over to using Rowan to manage Rowan until we get to the point where there are Rowan hybrid browser support in tODE and Gs_Jade ... I'm very close to having that for tODE and you are probably close as welll..

The upshot is that you need to create a class using the rwSubclass* family of methods then you should be able to add metnods to the class as part of the packaged class or as part of an extension in another (existing package) ...
