### ISSUE TITLE
Jadeite: "UndefinedObject does not understand #bitAnd:"

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#152]
I copied the source that caused the error in the left hand window and pasted into a system browser, and you can see that there are compile errors in the method and the method browser seems to not be able to handle them:
![image](https://user-images.githubusercontent.com/623951/39666482-09e52706-5059-11e8-8b97-d8b81487f4ed.png)

**Comment by ericwinger** [comment]
Could you copy/paste the problematic text into this issue?  Thanks.

**Comment by dalehenrich** [comment]
I don't have it anymore ... have you tried reproducing with any old syntax error?

When I get back into a jadeite exe I'll give it a try ...
