### ISSUE TITLE
Fix class comment

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#158]
Entering Class Documentation in the tab of the same name does not work. It should for alpha.

**Comment by ericwinger** [comment]
I don't think this is needed. Please open new bug if problems with class comments.

**Comment by LisaAlmarode** [comment]
When you try to edit the class comment now, it says "This functionality not available.  Commit your changes at the project level".  Which is confusing...

**Comment by ericwinger** [comment]
Does Ctrl-S work for you @LisaAlmarode ?

**Comment by LisaAlmarode** [comment]
Yes.  But I never use keyboard shortcuts or icons.  I'm a menu kind of person.

**Comment by ericwinger** [comment]
Thanks for confirming, the Save popup menu option is the problem. It's hooked to the wrong method `savePackage`
