### ISSUE TITLE
package tab visibilty

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#164]
According to HR 9824, the package tabs in system browser are not visible when not logging in as SystemUser or DataCurator ... my guess is that the package tabs are enabled only when session methods are enabled (i.e. GLASS installed) ... We probably want to change that although I haven't tested what happens when running without session methods enabled, but it should work as long as users aren't trying to use packages that rely on session methods ...

**Comment by dalehenrich** [comment]
Confirmed that `GsPackagePolicy current disable; System commit` followed by logout/login does indeed reproduce the issue reported ing HR9824..

As we discussed, I don't think that Jadeite behavior should have a dependency upon session methods being enabled, however, for the time being --- until Rowan has been tested without session methods enabled --- I will recommend that customers execute the following code to enable Rowan for non DataCurator/SystemUsers ... if we get push back then we will revisit ...

**Comment by dalehenrich** [comment]
@ericwinger isn't this one fixed by your recent Jadeite checkin?

**Comment by dalehenrich** [comment]
,,, candidate is ready with #165 fixes

**Comment by ericwinger** [comment]
> @ericwinger isn't this one fixed by your recent Jadeite checkin?
>... presumably you are waiting to check against candidate ... coming soon
>,,, candidate is ready with #165 fixes

I disabled the package policy checks which I'll test on your latest candidate checkin. If I can login as non-SystemUser without problem I'll close the bug.

**Comment by ericwinger** [comment]
Verified in Jadeite Alpha2.0
