### ISSUE TITLE
incorrect class definition string

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#17]
Sending method classCreationTemplateForClass:hybridBrowser: to RowanDefinitionService results in this class definition string, however this method does not appear to be implemented in Rowan: 

Object rwSubclass: 'RowanDefinitionService'
	instVarNames: #( definition)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	inDictionary: ''
	category: 'Rowan-Services'
	options: #()

**Comment by dalehenrich** [comment]
ah ... I removed the inDictionary: arg from the actual messages and missed changing the template ... poor test coverage ..

**Comment by ericwinger** [comment]
No problem. I'll pick the change up tomorrow. 

fyi - I'm not going to test your new readme instructions tonight. I'll test it tomorrow.

**Comment by dalehenrich** [comment]
I'll be in the office tomorrow, so that'll be a good time to try out something new ...
