### ISSUE TITLE
Recompiling method fails

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#18]
In a rowan-aware class, you can create a method by sending rwCompileMethod:category: to a behavior. The creation of new methods works fine.  

Make a change to the method and compile again and it fails with this error. 

a UserDefinedError occurred (error 2318), reason:halt, Internal error -- no existing LoadedMethod found for the old compiledMethod.

UserDefinedError (AbstractException) >> _signalWith: @6 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsPackageSymbolDictionary (Object) >> error: @6 line 7
[] in RwGsPackageSymbolDictionary >> addRecompiledMethod: @38 line 35
IdentityKeyValueDictionary >> at:ifAbsent: @26 line 19
RwGsPackageSymbolDictionary >> addRecompiledMethod: @15 line 32
RwGsMethodSourceSymbolDictPatch >> installSourcePatch @3 line 5
[] in RwGsPatchSetBasic >> updateMethodDictionaries @13 line 10
[] in Set >> do: @8 line 11
KeyValueDictionary >> keysDo: @20 line 18
Set >> do: @4 line 11
RwGsPatchSetBasic >> updateMethodDictionaries @4 line 10
RwGsPatchSetBasic >> apply @19 line 24
RwGsImage class >> applyModification: @11 line 9
RwPrjLoadTool >> loadProjectSetDefinition: @14 line 13
[] in RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @69 line 55
[] in RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @79 line 63
[] in RwAbstractTool >> definitionsForClassNamed:ifFound:ifAbsent: @20 line 11
RwGsImage class >> loadedClassNamed:ifFound:ifAbsent: @10 line 11
RwPrjBrowserTool (RwAbstractTool) >> definitionsForClassNamed:ifFound:ifAbsent: @4 line 4
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @13 line 60
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @13 line 29
MyNewClass class (Behavior) >> rwCompileMethod:category: @8 line 4
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @12 line 7
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
[] in JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: @8 line 13
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @3 line 15
JadeServer64bit34 (JadeServer) >> sbSaveMethod: @13 line 9
JadeServer64bit34 (JadeServer) >> systemBrowserCommand @122 line 40
[] in JadeServer >> systemBrowserA: @23 line 10
Time class >> secondsElapsedTime: @6 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit34 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserA: @3 line 4
JadeServer64bit34 (JadeServer) >> systemBrowser: @3 line 2
[] in JadeServer64bit >> systemBrowser: @7 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit) >> systemBrowser: @3 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
Just a note. It might not be the second compile of the method that fails. It might be the second compile of a method _in a new session._

**Comment by dalehenrich** [comment]
okay ... I'll have to play with this ...

**Comment by ericwinger** [comment]
There was a double compile built in to Jade. When the second 'normal' compile was run after the rowan compile, things got wonky.
