### ISSUE TITLE
`Published` symbol dict missing from symbol list used to compile Jadeite?

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#187]
I've move `Rowan` class into **Published** for Issue #141 and get the following error trying to login:
![image](https://user-images.githubusercontent.com/623951/40089535-0fa3dc18-5861-11e8-9274-9e526d0bb56c.png)
I know that you will be doing indirect references to the services classes through **Rowan**, however, it appears that **Rowan** isn't resolved unless it is in **Globals**.

I took out the [workaround for Issue #162](https://github.com/dalehenrich/Rowan/issues/162#issuecomment-387546080) and got the above error ... 

Mainly a placeholder for what we will need to do, once I've got #141 resolved ...

**Comment by ericwinger** [comment]
I believe this is fixed in my latest Jadeite Alpha2.0.1  2d070a8

**Comment by dalehenrich** [comment]
- [ ] confirm Jadeite Alpha2.0.1 works with latest candidate branch
- [ ] remove Rowan work around and reconfirm that Jadeite is working with only Rowan visible in Published

**Comment by dalehenrich** [comment]
Looks like **RowanService** also needs a `Rowan class>>serviceClass` method... screenshot logging in as DataCurator:
![image](https://user-images.githubusercontent.com/623951/40207345-e573ba7e-59e8-11e8-8f94-b58dfe34ac15.png)

**Comment by dalehenrich** [comment]
If you make this changes to your checkout you will be able see the issue:
```
rogue:Rowan>git diff
diff --git a/platforms/gemstone/topaz/3.2.15/rowan/Rowan-Bootstrap.gs b/platforms/gemstone/topaz/3.2.15/rowan/Rowan-Bootstrap.gs
index 150201a..6b2f29b 100755
--- a/platforms/gemstone/topaz/3.2.15/rowan/Rowan-Bootstrap.gs
+++ b/platforms/gemstone/topaz/3.2.15/rowan/Rowan-Bootstrap.gs
@@ -676,14 +676,14 @@ currentOrNil
 #   and Issue #187 #   (revolve references to Rowan when it is in Published 
 #   and not Globals
 #
-   run
-  #(Rowan RowanClassService RowanMethodService RowanPackageService RowanProjectService 
-    RowanService RowanServicePreferences) do: [:className |
-      | assoc |
-      assoc := RowanKernel associationAt: className.
-      Globals add: assoc ].
-%
-  commit
+#   run
+#  #(Rowan RowanClassService RowanMethodService RowanPackageService RowanProjectService 
+#    RowanService RowanServicePreferences) do: [:className |
+#      | assoc |
+#      assoc := RowanKernel associationAt: className.
+#      Globals add: assoc ].
+#%
+#  commit
```

**Comment by ericwinger** [comment]
Yup, forgot about that.  I'll make the change and get a new .exe out right away.

**Comment by dalehenrich** [comment]
Will you be able to eliminate reference or do you need a Rowan class-side access method?

**Comment by ericwinger** [comment]
I'll need the class-side access method. I'll send `Rowan serviceClass`

**Comment by dalehenrich** [comment]
I've made the changes for a #serviceClass method, but if you don't need it I won't commit and push ...

**Comment by ericwinger** [comment]
It's actually good to have especially for future development.

**Comment by dalehenrich** [comment]
I'll do the commit and push right now ...

**Comment by ericwinger** [comment]
Can I load Rowan in Rowan?!

**Comment by dalehenrich** [comment]
nope ... you have to be patient ... the commit that gets tagged with v0.1.0-alpha will be the commit where you will be able to start using Rowan to update Rowan ...

**Comment by ericwinger** [comment]
Believe this works with new Jadeite.exe I just published.
