### ISSUE TITLE
Compiled references to classes with new versions can be incorrect, if class itself has a new version

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#188]
I've been able to login in to the latest candidate branch Rowan (sha f6aa2dd). However, I believe that the method reference to the services classes will cause a problem. e.g. `RwGsPlatform>>projectServiceClass, etc` 

If I compile a new version of a service class, this method will still point to the old version of the class. At least that's what I saw when I was implementing support for this in Jadeite. 

I fixed the problem by having the new methods reference the class through the user profile. There may be better solutions. 
```
projectServiceClass
^System myUserProfile symbolList objectNamed: #RowanProjectService
```

**Comment by dalehenrich** [comment]
Compiled references to a class with a new version *should not* cause a problem - compiled in references to classes *should* compile in a reference to the association, not a direct reference to the class itself ... if you are seeing an issue, then either the method is compiled with a reference to the wrong association (possible given some of the things that I'm doing during the bootstrap step --- although I haven't explicitly changed the bootstrap process in my recent work, it is always possible that something odd might be going on) and/or we are looking at a completely different class ...

I will take a look and see if I can characterize the issue further ...

**Comment by ericwinger** [comment]
It's not inconceivable that my other image got into a bad state. 
Even though your change looks like what I did in my development environment, I'm not seeing the problems since I got your code. 

I'll close the issue and reopen if I see anything similar.

**Comment by dalehenrich** [comment]
Okay ... this little experiment (run in a fresh build) indicates that they are all pointing at the same class:
```smalltalk
| assoc |
assoc := RowanKernel associationAt: #RowanProjectService.
{Rowan projectServiceClass asOop.
RowanProjectService asOop.
assoc value asOop.
(System myUserProfile symbolList objectNamed: #RowanProjectService) asOop}
 anArray( 40154113, 40154113, 40154113, 40154113)
```
This doesn't rule out different associations --- which could also lead to your problem ... I will poke around a bit more --- while the iron is hot ...

**Comment by ericwinger** [comment]
What happens if you compile a new version of the class?

**Comment by dalehenrich** [comment]
What happens when you compile a new version of the class?

**Comment by ericwinger** [comment]
Heh - touche. So far I don't see any problems.

**Comment by dalehenrich** [comment]
Right now I am trying to figure out how to determine whether or not there is an association compiled into the methods (the most likely explanation for a problem if there is one ... is that a direct reference to the class is compiled into the method --- I seem to recall that this is actually done in some cases, especially for Kernel classes. I am not seeing literal references to the name of the class, when I query the method (which is beginning to look suspicious), but I may be doing it wrong. I will probably need to work with Allen to verify that the methods do indeed contain references to the associations and if not find out what we need to do to guarantee that associations are used ...

**Comment by dalehenrich** [comment]
Okay ... I think that the final answer is that things do look correct in the current build ... the following confirms that we are referencing the proper associations in each of the methods that reference the class:
```Smalltalk
(ClassOrganizer new referencesToObject: (RowanKernel associationAt: #RowanProjectService))
	collect: [:meth | meth inClass printString, (meth inClass isMeta ifTrue: [' class >>'] ifFalse:[ '>>']), meth selector]
 anArray( 
'RowanPackageService>>createSamplePackage', 
'RowanPackageService>>createPackageNamed:inProject:', 
'RowanPackageService>>createPackage',
'RwGsPlatform>>projectServiceClass', 
'RwRowanProjectIssuesTest>>testIssue150_branches') 
```
and this confirms that both RowanKernel and Globals (my workaround while waiting for you to change Jadeite) reference the same assocation:
```smalltalk
{(RowanKernel associationAt: #RowanProjectService) asOop.
(Globals associationAt: #RowanProjectService)  asOop
} anArray( 34839809, 34839809)
```

Sooo we're good unless we catch it misbehaving ...

**Comment by dalehenrich** [comment]
It seems that I have "caught it misbehaving ..."...

I've written a test with a reference to **RwProjectConfigurationVisitor** compiled into it ... :
```smalltalk
testVisitProjectCompoundConfiguration

	| url rowanSpec config visitor |
	rowanSpec := (Rowan image _projectForNonTestProject: 'Rowan') specification.
	url := 'file:' , rowanSpec repositoryRootPath , '/test/configs/RowanProjectCompoundConfiguration.ston'.

	config := RwProjectCompoundConfiguration fromUrl: url.

	visitor := RwProjectConfigurationVisitor new.
	visitor visit: config.
```
However, as Eric noted above, the class has started misbehaving in that it is not responding properly to messages ... and this time, I was able to confirm that association for the **RwProjectConfigurationVisitor** class compiled into the method does not match the current association present in `RowanKernel` symbol dictionary (the array should not be empty):
```smalltalk
(ClassOrganizer new referencesToObject: 
	(RowanKernel associationAt: #RwProjectConfigurationVisitor))
	collect: [:meth | 
		meth inClass printString, 
			(meth inClass isMeta 
				ifTrue: [' class >>'] 
				ifFalse:[ '>>']), meth selector]
 anArray( )
```
Since the problem does not seem to be easily reproducible I will spend some time examining the logs and my memory to see if I can reconstruct the work that I've done in this stone leading to this problem ...

**Comment by dalehenrich** [comment]
I've got a reproducible test case (based on commit 9be1e4cf86f4e8bed6742304b05dd4c8f2cf29f0):
```smalltalk
run
Object rwSubclass: 'RwProjectConfigurationVisitor'
	instVarNames: #( packageNames visitedConfigurationNames xxx)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'Rowan-Configurations'
	options: #().
RwAbstractTest rwSubclass: 'RwProjectConfigurationsTest'
	instVarNames: #( xxx)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'Rowan-Tests'
	options: #().
Object rwSubclass: 'RwProjectConfigurationVisitor'
	instVarNames: #( packageNames visitedConfigurationNames xxx yyy)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'Rowan-Configurations'
	options: #().
RwProjectConfigurationsTest debug: #testVisitProjectCompoundConfiguration
%
```
Note that the intermediate new version of **RwProjectConfigurationsTest** is *required*...

Without the new version of **RwProjectConfigurationsTest**, the `yyy` instance variable is visible, which indicates the method is compiled with a reference to the correct association:
```
-----------------------------------------------------
GemStone: Error         Nonfatal
a Halt occurred (error 2709)
Error Category: 231169 [GemStone] Number: 2709  Arg Count: 1 Context : 38843905 exception : 38831617
Arg 1: [20 sz:0 cls: 76289 UndefinedObject] nil
topaz 1> fr 4
4 RwProjectConfigurationsTest >> testVisitProjectCompoundConfiguration @15 line 12   [methId 40497153]
    receiver [38830593 sz:1 cls: 39994625 RwProjectConfigurationsTest] aRwProjectConfigurationsTest
    visitor [38828801 sz:4 cls: 38836737 RwProjectConfigurationVisitor] aRwProjectConfigurationVisitor
    config [38828033 sz:5 cls: 40195329 RwProjectCompoundConfiguration] aRwProjectCompoundConfiguration
    url [38827265 sz:83 cls: 74753 String] file:$ROWAN_PROJECTS_HOME/Rowan/test/configs/RowanProjectCompoundConfiguration.ston
    rowanSpec [41985281 sz:10 cls: 34902273 RwSimpleProjectSpecification] aRwSimpleProjectSpecification
(skipped 1 evaluationTemps)
topaz 1> obj1 @38828801
[38828801 sz:4 cls: 38836737 RwProjectConfigurationVisitor] a RwProjectConfigurationVisitor
  packageNames        [38825729 sz:5 cls: 102401 Set] a Set
  visitedConfigurationNames [38825217 sz:5 cls: 102401 Set] a Set
  xxx                 [20 sz:0 cls: 76289 UndefinedObject] nil
  yyy                 [20 sz:0 cls: 76289 UndefinedObject] nil
```
With the new version of RwProjectConfigurationsTest created, the `yyy` instance variable is not seenm indicating the association referencing RwProjectConfigurationVisitor is not correct:
```
-----------------------------------------------------
GemStone: Error         Nonfatal
a Halt occurred (error 2709)
Error Category: 231169 [GemStone] Number: 2709  Arg Count: 1 Context : 38816513 exception : 38820609
Arg 1: [20 sz:0 cls: 76289 UndefinedObject] nil
topaz 1> fr 4
4 RwProjectConfigurationsTest >> testVisitProjectCompoundConfiguration @15 line 12   [methId 38816769]
    receiver [38841345 sz:2 cls: 38818817 RwProjectConfigurationsTest] aRwProjectConfigurationsTest
    visitor [38814721 sz:3 cls: 38819329 RwProjectConfigurationVisitor] aRwProjectConfigurationVisitor
    config [38813953 sz:5 cls: 40195329 RwProjectCompoundConfiguration] aRwProjectCompoundConfiguration
    url [38813185 sz:83 cls: 74753 String] file:$ROWAN_PROJECTS_HOME/Rowan/test/configs/RowanProjectCompoundConfiguration.ston
    rowanSpec [41985281 sz:10 cls: 34902273 RwSimpleProjectSpecification] aRwSimpleProjectSpecification
(skipped 1 evaluationTemps)
topaz 1> obj1 @38814721
[38814721 sz:3 cls: 38819329 RwProjectConfigurationVisitor] a RwProjectConfigurationVisitor
  packageNames        [38811649 sz:5 cls: 102401 Set] a Set
  visitedConfigurationNames [38811137 sz:5 cls: 102401 Set] a Set
  xxx                 [20 sz:0 cls: 76289 UndefinedObject] nil
```
Now it's time to characterize and fix ...

**Comment by dalehenrich** [comment]
It appears that the source of this problem lies in how RwGsPatchSet creates the tempSymbols:
```smalltalk
setupForApply

	"Copy the entire namespace from the user's transient SymbolList into a temporary SymbolDictionary in a temporary 
	SymbolList, the tempSymbols. The tempSymbols, once suitably modified, will be used as the environment in which 
	to compile methods during this apply operation."

	| symbolList |
	tempSymbols := SymbolDictionary new.
	symbolList := Rowan image symbolList.	"If there are any duplicated symbols, we only want the one that will be found first one, 
	so we copy in reverse order of search order, thereby overwriting later definitions with earlier ones."
	symbolList
		reverseDo: [ :dict | dict keysAndValuesDo: [ :aKey :aValue | tempSymbols at: aKey put: aValue ] ]
```
New associations are always created for all classes, however, in RwGsMethodPatch>>compileUsingNewClasses:andExistingClasses:, we are using this symbol dictionary with new Associations for each class as a symbol list for adding and recompiling methods for classes with new versions:
```smalltalk
compileUsingNewClasses: createdClasses andExistingClasses: tempSymbols

	| sourceString symbolList protocol |
	self primeBehaviorNewClasses: createdClasses andExistingClasses: tempSymbols.
	behavior
		ifNil: [ self error: 'Class ' , self className printString , ' not found.' ].

	sourceString := methodDefinition source.
	symbolList := SymbolList with: tempSymbols.
	protocol := (methodDefinition propertyAt: 'protocol') asSymbol.
	compiledMethod := behavior
		compileMethod: sourceString
		dictionaries: symbolList
		category: protocol
		intoMethodDict: false
		intoCategories: nil
		intoPragmas: nil
		environmentId: self methodEnvironmentId
```
will now create a fix and create some tests to cover this area ... to expose this bug we need to have new versions of at two interrelated classes ...
