### ISSUE TITLE
Revamp Configuration/Spec class structure

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#189]
With issue #185, it became clear that besides a probable bug in the way Rowan handles moving packages between symbol dictionaries,  the location of the platform properties (session method package mapping and symbol dictionary package mapping)  information like the following is wrong:
```ston
{
	#defaultSymbolDictName : 'RowanKernel',
	#defaultUseSessionMethodsForExtensions : false,
	#packageNameToPlatformPropertiesMap : {
		'Rowan-Cypress-Kernel' : { 'symbolDictName' : 'Globals' },
		'Rowan-GemStone-Kernel' : { 'symbolDictName' : 'Globals' },
		'Rowan-Tools-Kernel' : { 'symbolDictName' : 'Globals' },
		'GemStone-Interactions-Kernel' : { 'symbolDictName' : 'Globals' },
		'Rowan-GemStone-3215' : { 'symbolDictName' : 'Globals' },
		'Rowan-GemStone-Loader' : { 'symbolDictName' : 'RowanLoader' }
		}
	}
```
Currently this information is loaded and stored along with the project specification, however, we do not reload the spec information when doing an update so any changes made to the project specification on disk will not be loaded into the stone and this can lead (at least partially) to the problems seen in #185.

I have been planning for a while to add conditional loading to Rowan configurations to allow for the management of platform specific packages and after discussions with @rjsargent am thinking that adding groups in addition to platform mapping as well as incorporating the package mapping scheme into the configuration is  good idea and at the moment the object/specification structure would like the following:
```ston
 RwProjectLoadConfiguration{
	#name : 'Rowan',
	#platformPackages: {
		[ 'common' ] : {
                        'core': {
				#packageNames : [
					'Rowan-Url-Core',
					'Rowan-Cypress-Core',
					'Rowan-Cypress-Kernel',
					'Rowan-Definitions',
					'Rowan-Specifications',
					'Rowan-Configurations',
					'Rowan-Core',
					'Rowan-Tools-Core',
					'Rowan-Tools-Kernel'
					],
				#configurationNames : [ ]
				},
			'tests' : {
				#packageNames : [
					'Rowan-Tests'
					],
				#configurationNames : [ ]
				},
			'deprecated' : {
				#packageNames : [
					'Rowan-Deprecated'
					],
				#configurationNames : [ ]
				}
			},
		[ 'gemstone' ] : {
                        'core': {
				#packageNames : [
					'Rowan-Services-Extensions',
					'Rowan-Services-Core',
					'Rowan-GemStone-Core',
					'Rowan-GemStone-Kernel',
					'Rowan-GemStone-Loader',
					'Rowan-GemStone-Loader-Extensions'
					],
				#configurationNames : [ 
					'Tonel',
					'STON'
					]
				},
			'tests' : {
				#packageNames : [
					'Rowan-Services-Tests'
					],
				#configurationNames : [ ]
				},
			},
		[ 'gs3.2.[15-].x' ] : {
                        'core': {
				#packageNames : [
					'Rowan-GemStone-3215',
					'Rowan-Url-3215',
                			'GemStone-Interactions-Core',
					'GemStone-Interactions-Kernel'
					],
				#configurationNames : [ ]
				}
			}
		},
	#namedSpecs : {
		[ 'gemstone' ] : {
			'SystemUser_load' : {
				#defaultSymbolDictName : 'RowanKernel',
				#defaultUseSessionMethodsForExtensions : false,
				#packageNameToPlatformPropertiesMap : {
					'Rowan-Cypress-Kernel' : { 'symbolDictName' : 'Globals' },
					'Rowan-GemStone-Kernel' : { 'symbolDictName' : 'Globals' },
					'Rowan-Tools-Kernel' : { 'symbolDictName' : 'Globals' },
					'GemStone-Interactions-Kernel' : { 'symbolDictName' : 'Globals' },
					'Rowan-GemStone-3215' : { 'symbolDictName' : 'Globals' },
					'Rowan-GemStone-Loader' : { 'symbolDictName' : 'RowanLoader' }
					}
			},
			'Standard_load' : {
				#defaultSymbolDictName : 'UserGlobals',
				#defaultUseSessionMethodsForExtensions : false
				}
			}
		}
	#comment : ''
}
```
There are two primary sections: `platformPackages` and `namedSpecs`. Package names and *included* configurations are listed in `platformPackages` and the GemStone-specific package mappings (from the spec) are listed in the `namedSpecs` section.

The `platform key` (for both  `platformPackages` and `namedSpecs`)  is an array of platform patterns that when matched by the current platform will cause the name `groups` to be included in a load  ... `group` names are specified by the developer for a load.

All packages will be listed in at least one group, as packages are not individually available to developers when loading projects.
All package mappings will also be listed in one group and if a package mappings group matches a name in the `group` list specified for a load, the package mappings will be used to drive the load

**Comment by rjsargent** [comment]
"The platform key ... is an array of platform strings that when matched by the current platform ..."
I suggest changing "platform strings" to "platform patterns"
and clarifying that it only takes one pattern to match for the array to be considered matched.

**Comment by dalehenrich** [comment]
call Issue #189 closed ... remaining work involves #185 bugfix and implementation of project references ... which should be encapsulated in a separate issue
