### ISSUE TITLE
Lost ability to add a package & project (or at least see it) 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#19]
Not quite sure what I've done but Package/Project creation quit working mysteriously. 

In the test_rowan_340 repository, you can send RowanPackageDefinitionService>>createPackageNamed:inProject:

The default symbol dictionary name is 'SampleSymbolDictionaryName'.  No walkbacks or failure messages in the transcript. It just doesn't show up in the category list. 

Maybe pilot error, but I'm creating the packages the same way Dale and I did this morning.

**Comment by dalehenrich** [comment]
What does the category list do to list symbolDictionaries? Can you resolve `SampleSymbolDictionaryName` in an inspector?

I might have to debug this with you tomorrow

**Comment by ericwinger** [comment]
_What does the category list do to list symbolDictionaries?_ 

Not really sure yet. 

_Can you resolve SampleSymbolDictionaryName in an inspector?_

When I retry with the same package, I get a "tried to load an existing package" error. So it looks like it does something.  But my limited inspector doesn't show me anything. 

_I might have to debug this with you tomorrow_

Sure, whatever works best.

**Comment by ericwinger** [comment]
'Rowan image loadedProjects' does show all the projects I created with the packages. ... fyi

**Comment by dalehenrich** [comment]
projects are managed in a different manner than SymbolDictionaries ... (symbolDictionaries own the classes, class extensions and methods) ...

**Comment by dalehenrich** [comment]
I think this is issue was addressed ... new issues may pop up though:)
