### ISSUE TITLE
Running hybrid browser tool test leaves RowanTestData around

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#20]
Not sure if this is a bug, but opening issue if it is undesirable. 

Running RwHybridBrowserToolTest sunit tests creates the symbol dictionary RowanTestData and leaves around the classes SimpleHybrid1, etc.

**Comment by dalehenrich** [comment]
Yes it does leave junk around ... which has been convenient for using tests to generate data for the browser ...

This [chunk of code](https://github.com/dalehenrich/Rowan/blob/master/src/tonel/Rowan-Tode/TDRowanProjectBrowser.class.st#L76-L110) deletes all of the existing projects ... this code supplies the list of projects:
```Smalltalk
(Rowan image loadedProjects
		collect: [ :each | 
			TDRowanProjectDefinition new
				projectName: each name;
				yourself ])
sortWithBlock: [ :a :b | a projectName <= b projectName ]
```
Note That the TDRowanProjectDefinition is an intermediate object that isn't needed loadedProjects produced by the above, and loadedProjects used in the deletion code ...

**Comment by ericwinger** [comment]
Not a big deal to leave it around if that is intentional.

**Comment by dalehenrich** [comment]
as of recent checkins ... tests no longer leave turds around in the project list ... test symbol dictionaries are still currently left around ...
