### ISSUE TITLE
generated project has lfs not crs and not readable on unix

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#217]
Running jadeite on windows and creating a project using the project creation script; the spec that is created uses cr and not lf as line endings.  It can't be viewed using cat, and vi shows the lines without endings, just separated by ^Ms.  GUI tools like jadeite and gbs handle this but e.g from topaz:

topaz 1> run
(GsFile openReadOnServer: '/benton1/users/gsadmin/GS643215/TomatoProject1/Tomato1/specs/Tomato1.ston') contents
%
}wSimple]default'default's : [ames : [ject using the Tomato System',',
topaz 1> 

Currently visible in 
/benton1/users/gsadmin/GS643215/TomatoProject1/Tomato1/specs/Tomato1.ston

The other generated files have okay EOL chars.

**Comment by dalehenrich** [comment]
fixed ...
