### ISSUE TITLE
Tools visibility issues as DataCurator

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#222]
If you want to use the Rowan API, you need to be able to see the classes e.g RwProjectTool or RwPkgAdoptTool, so you can see the methods are available and read the method comments.  

Presumably it is supported to use these tools as DataCurator; but these classes are not visible from Jadeite as DataCurator.  

One of the closed issues suggests you can add the tools dictionary to the transient symbol dictionary.  This is not something that we should have to have users execute; the classes either should or should not be visible/usable.

| transient size dict |
transient := GsSession currentSession symbolList.
size := transient size.
dict := (AllUsers userWithId: 'SystemUser') objectNamed: 'RowanTools'.
transient insertObject: dict at: size + 1.

While executing the above code does make classes visible, clicking on any of them in the jadeite browser (packages view), throws an error in trying to create the class template.

MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'value'

MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @9 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
RowanClassService >> classFromName @5 line 3
RowanClassService >> classCreationTemplate @3 line 3
JadeServer64bit32 (JadeServer) >> sbUpdateClassInfo @15 line 10
JadeServer64bit32 (JadeServer) >> systemBrowserUpdate @7 line 8
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @189 line 62
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
Good catch ... I agree that the "This is not something that we should have to have users execute", however, we are not going to add a new feature to Jadeite (at this point in time). If the RowanTools symbol dictionary survives through the summer, then making it easy to expose the tools api will be added:)

**Comment by dalehenrich** [comment]
@LisaAlmarode could you add a separate issue about having to execute code to view the tools api as DataCurator?

with daf5168, the browser should be functioning correctly
