### ISSUE TITLE
Need to be able to see the tools API as DataCurator

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#224]
You need to execute weird funky code to see the rowan tools classes if you are not SystemUser.  There must be a better way.

| transient size dict |
transient := GsSession currentSession symbolList.
size := transient size.
dict := (AllUsers userWithId: 'SystemUser') objectNamed: 'RowanTools'.
transient insertObject: dict at: size + 1.

**Comment by dalehenrich** [comment]
We can wrap this in an api call in the **RwPrjBrowserTool** perhaps?

**Comment by dalehenrich** [comment]
#exposeRowanToolsSymbolDictionary?

**Comment by LisaAlmarode** [comment]
While this makes the Tools classes resolvable, and visible via sorting through the packages, it does not add the SymbolDictionary to my SymbolList.  And I can't do a class lookup on RwPrjBrowserTool, nor a method lookup on exposeRowanToolsSymbolDictionary.

This is related to issue 214 but I'm reopening it here specifically since this severely limits usability...

**Comment by dalehenrich** [comment]
... there's nothing more that Rowan can do about the Jadeite bug, but leaving this issue open pending the fix to issue #214 is fine

**Comment by dalehenrich** [comment]
... after conversation with @LisaAlmarode we should expand the api to include an option to add the Rowan symbol dictionaries to the persistent symbol list as well ...

**Comment by dalehenrich** [comment]
With commit ef8393d we've got methods that support adding Rowan symbol dictionaries to the persistent symbol list ... closing now
