### ISSUE TITLE
Rowan project sample's directory cleanup

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#235]
The Jadeite project load defaults to the spec files that are in the Rowan/samples directory, specifically 
file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample1.ston

As DataCurator, 1 and 4 are working, but 2 and 3 need cleanup.

Loading 2, (that is, using Jadeite to specify file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample2.ston), you get a STONReaderError occurred (error 2710), , expected
This is a known typo that was fixed in some other issue for RowanSample4.

Loading $ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample3.ston), it doesn't give an error but it doesn't show a sha and the cloned directory.  After some cleanup it appears that it's wanting to fetch from github the branch issue150 when it should be issue_150.  

When I manually clone the correct branch of RowanSample3, then load runs into the typo again, 
STONReaderError occurred (error 2710), , expected

This typo occurs loading both ways:
   file:$ROWAN_PROJECTS_HOME/RowanSample3/rowan/specs/RowanSample3.ston
   file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample3.ston

**Comment by dalehenrich** [comment]
Loading RowanSample[1-4] sample is working ... master/sample branches for RowanSample[1-2], issue_150 branch for RowanSample2 ... master branch for RowanSample4
