### ISSUE TITLE
Need discussion for long-term Rowan Diffs and Dirty State

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#24]
What is the api for determining a Rowan object's change/modification/dirty state?  

I found RwLoadedPackage inst var isDirty, but that is only for packages and I would expect that any RwLoadedThing should have an api for identifying changes. (Maybe not RwLoadedMethod)

**Comment by ericwinger** [comment]
In discussion with Dale, we need a whiteboard session to discuss Rowan "diffs"

**Comment by dalehenrich** [comment]
I believe that it is time to address this puppy

**Comment by dalehenrich** [comment]
Projects and packages can be marked dirty or not dirty ... but here is the odd thing about the current implementation ... at the end of a load, the loaded projects/packages are marked not dirty, but the loaded projects/packages are marked dirty when the loaded state is changed ... something that happens during the load ... so by definition, the only time a project/package would be left dirty is if the load did not complete ...

I think that a dirty project/package is one that does not match disk (i.e., the image is dirty relative to disk). So I think that projects/packages should be marked dirty when they are modified (as is currently the case), but the project/packages should only be marked as **not dirty* when:
1. the project/package is written to disk
2. the project/package is loaded from disk

**Comment by dalehenrich** [comment]
I discovered that I had not covered all of the entry points for doing loads from disk ... additional patches forthcoming

**Comment by dalehenrich** [comment]
ready for @ericwinger to use `isDirty` for packages and projects to display dirty state in Jadeite

**Comment by dalehenrich** [comment]
It doesn't appear the that the project list is showing dirty projects:
![image](https://user-images.githubusercontent.com/623951/39657801-4166929e-4fc0-11e8-8a6e-acf41cc4fde3.png)
From the snapshot, you can see that two packages are modified and from the changes browser you can see that there are two methods modified and from the printit of the loaded package and the RwProject, that the package is dirty ... I've included the help for jadeite so you can see the version.

BTW, it would help if you would tell us the full version name of the new jadeite.exe, so I can correlate the Jadeite that I'm using with the email in which you announce the new version I believe that I copied the new jadeite over --- I _am_ seeing dirty packages, just no dirty projects so I think I've got the latest jadeite

**Comment by ericwinger** [comment]
Good point about giving you the version on my email. I'll do that from now on. 

Looks the version might be off.  What I *thought I* published was Alpha1.0.1-4-g5b30c6a. 

That version is showing me project dirty.

**Comment by dalehenrich** [comment]
Announcing the SHA of the commit that I should use when grabbing the jadeite.exe is probably a good thing as well ... I can't tell what version of Jadeite I'm going to get when I look at the git checkout ... having both in the mail means that I can look at git and confirm that I've got the correct SHA checkout when I do the copy and I can cross check the version that I'm actually running with the version announced in the email to make sure that the executable is the one that I copied to the shared directory...

**Comment by dalehenrich** [comment]
see the dirtiness now and the recent SHA/version in email works well
