### ISSUE TITLE
Rowan Load problem with a user with a world-none security policy

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#242]
related to issue 241, except that SymbolLists aren't "changed".

If you load rowan, then create a user Lisa with their own security policy that is world none, and then login as DataCurator and try to create a project (the adopt-and-commit), you get an exception.

a SecurityError occurred (error 2115), An attempt was made to read the object with ID 52693761 in objectSecurityPolicyId 9 with insufficient authorization. nil

This is since DataCurator is looking up projects but doesn't have read access to Lisa's SymbolList. You can reproduce this exception using by simply logging in as DataCurator and executing:
(AllUsers userWithId: 'Lisa') objectNamed: #'UserGlobals'.  This is a base GemStone behavior; SystemUser can do the lookup, but not DataCurator. 

This is the exception:

SecurityError (AbstractException) >> _signalFromPrimitive: @5 line 15
UserProfile >> objectNamed: @1 line 1
RwGsImage class >> _loadedProjectRegistryForUserId: @3 line 4
[] in  ExecBlock1 (RwGsImage class) >> loadedProjectNamed:ifAbsent: @6 line 16
UserProfileSet (IdentityBag) >> do: @6 line 8
[] in  ExecBlock0 (RwGsImage class) >> loadedProjectNamed:ifAbsent: @2 line 11
StringKeyValueDictionary >> _stringAt:ifAbsent: @5 line 8
StringKeyValueDictionary >> at:ifAbsent: @8 line 10
RwGsImage class >> loadedProjectNamed:ifAbsent: @5 line 8
RwSimpleProjectSpecification (RwSpecification) >> register @4 line 4
RwPrjCreateTool >> createProjectFor:format: @32 line 38
RwPrjCreateTool >> createProjectFor:format:root:configsPath:repoPath:specsPath: @21 line 17
RwPrjCreateTool >> createGitBasedProject:packageNames:format:root: @6 line 11
Executed Code  @7 line 9
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by LisaAlmarode** [comment]
To reproduce (verified 72dbd08):

(1) get a fresh extent.
(2) install Rowan

(3) Create a user (done as SystemUser), using:

login
run
| securityPolicy newUser |
      securityPolicy := GsObjectSecurityPolicy new
        ownerAuthorization: #write;
        yourself.
      System commit.
      newUser := (AllUsers 
        addNewUserWithId: 'Lisa'
        password: 'asil'
        defaultObjectSecurityPolicy: securityPolicy)
        addPrivilege: #CodeModification;
        addPrivilege: #UserPassword;
        addPrivilege: #OtherPassword;
        yourself.
      securityPolicy owner: newUser 
%
commit

( Note that I do steps 2 and 3 using script /export/benton1/users/gsadmin/GS643215/data/installRowan)

(4) As DataCurator, login and try to create project:

set user DataCurator pass swordfish
login
run
Rowan projectTools create
	createGitBasedProject: 'ExampleProject'
	packageNames: #('PackageOne' 'PackageTwo')
	format: 'tonel'
	root: '$ROWAN_PROJECTS_HOME'.
%

error:
ERROR 2115 , a SecurityError occurred (error 2115), An attempt was made to read the object with ID 48243201 in objectSecurityPolicyId 9 with insufficient authorization. nil (SecurityError)

**Comment by dalehenrich** [comment]
thanks ... reproduced the problem and found the problem in my script to boot!
