### ISSUE TITLE
Need McPatch emulation

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#25]
This would be a short-term hack for showing differences in 'hybrid Jade' 

Note -Hybrid Jade is the 'quick and dirty' way to get Rowan development in Jade

**Comment by dalehenrich** [comment]
It is looking like I won't actually have to add a class called McPatch to get GsJade to display differences. I think that the code [here](https://github.com/jgfoster/Jade/blob/893b6ec8bfed0f04841504addb584a1d8a3dc74f/sources/Jade%20System%20Browser.pax#L594-L609):
```smalltalk
sbChangesInPackage: anOrderedCollection

	| current repository patch string |
	current := self mcWorkingCopyClass forPackage: (self mcPackageClass named: anOrderedCollection removeFirst).
	repository := anOrderedCollection removeFirst.
	repository := current repositoryGroup repositories detect: [:each | each description = repository].
	patch := current changesRelativeToRepository: repository.
	patch operations isEmpty ifTrue: [current modified: false].
	string := self 
		_mcDescriptionOfPatch: patch
		baseName: 'closest ancestor'
		alternateName: nil.
	writeStream 
		nextPutAll: 'changesInPackage'; lf;
		nextPutAll: string;
yourself.
```
can be changed to do the following and with the addition of some upcoming changes, should work fine:
```Smalltalk
sbChangesInPackage: anOrderedCollection
        "where anOrderedCollection is {packageName, projectName}"

        | patch string |
	patch := Rowan packageTools diff
		patchSpecUrl: (anOrderedCollection at: 2)
		packageName: (anOrderedCollection at: 1).
	string := self
		_mcDescriptionOfPatch: patch
		baseName: 'closest ancestor'
		alternateName: nil.
	writeStream
		nextPutAll: 'changesInPackage';
		lf;
		nextPutAll: string;
		yourself
```
We'll see tomorrow:)

**Comment by dalehenrich** [comment]
The fix was done on the gs_3215 branch -- I will merge the changes into the master branch shortly ...

**Comment by dalehenrich** [comment]
well ... it looks like Jade isn't cooperating in enabling the McPatch code when not connecting to an image with McWorkingCopy installed (Issue #61)

**Comment by dalehenrich** [comment]
issue #61 is closed, so I think we've got this one covered
