### ISSUE TITLE
Constraints set to classes that do not exist

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#255]
Reported by customer and reproduced. 

If you have a constraint on a class's instance variables and the constrainee class does not exist, loading the project errors with "a ArgumentTypeError occurred (error 2094), expected a Class".

It's defining the class as nil when creating the constraints object from the String:
anArray( anArray( #'aaa', String), anArray( #'bbb', nil))

Tonel file for class:

Class {
        #name : 'Demo',
        #superclass : 'Object',
        #instVars : [
                'aaa',
                'bbb',
                'ccc'
        ],
        #gs_constraints : [
                [
                        'aaa',
                        'String'
                ],
                [
                        'bbb',
                        'zSmallInteger'
                ]
        ],
        #category : 'PackageTwo'
}

-----
stack:

ArgumentTypeError (AbstractException) >> _signalFromPrimitive: @5 line 15
Object class (Metaclass3) >> _primSubclass:instVarNames:format:constraints:classVars:poolDictionaries:classInstanceVars: @1 line 1
Object class (Metaclass3) >> _subclass:instVarNames:format:constraints:classVars:poolDictionaries:classInstanceVars: @3 line 10
Object class (Class) >> _subclass:instVarNames:format:constraints:classVars:classInstVars:poolDictionaries:inDictionary:inClassHistory:description:options: @115 line 90
Object class (Class) >> subclass:instVarNames:classVars:classInstVars:poolDictionaries:inDictionary:newVersionOf:description:constraints:options: @14 line 42
RwGsClassVersioningSymbolDictPatch (RwGsClassPatch) >> basicCreateClassWithSuperclass: @20 line 19
RwGsClassVersioningSymbolDictPatch (RwGsClassPatch) >> privateCreateClassWithSuperclass: @2 line 4
RwGsClassVersioningSymbolDictPatch (RwGsClassPatch) >> privateCreateClassFor: @14 line 13
RwGsClassVersioningSymbolDictPatch (RwGsClassPatch) >> createClassFor: @2 line 4
RwGsClassVersioningSymbolDictPatch >> createClassFor: @4 line 7
RwGsPatchSet >> createClassNamed:fromWorkList:andClassesByName: @10 line 15
RwGsPatchSet >> createClassesFromWorklist:andClassesByName: @6 line 9
RwGsPatchSet >> createNewClassesAndClassVersions @10 line 13
RwGsPatchSet >> apply @6 line 9
RwGsPatchSet >> applyForNewClassVersions: @8 line 17
RwGsImage class >> applyModification:visitorClass:instanceMigrator: @21 line 25
RwGsImage class >> applyModification:instanceMigrator: @8 line 13
RwPrjLoadTool >> _loadProjectSetDefinition:instanceMigrator: @17 line 19
[] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
RwPrjLoadTool >> loadProjectNamed:instanceMigrator: @7 line 9
RwPrjLoadTool >> loadProjectNamed: @4 line 5
[] in  ExecBlock0 (RowanProjectService) >> loadProjectNamed: @4 line 3
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RowanProjectService >> loadProjectNamed: @2 line 4
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by LisaAlmarode** [comment]
I have verified that if you have two packages that each constrain an inst var to a class that is defined in the other package, and neither constraining class exists in the image prior to load... then you get this error when you try to load the project.  

There's a constructed example here:
/benton1/users/gsadmin/GS643215/myrowan/ExampleProject

**Comment by dalehenrich** [comment]
Looking at this test case, I am curious how you would be able to load them into a stone using .gs files ... neither class can be loaded as is, since they each have a constraint involving the other  ... is this the case that was seen in the HR? I do expect to attempt to allow this particular case, but I will see how it goes

**Comment by dalehenrich** [comment]
need tests for constraints on multiple classes in a hierarchy (9a2a72c)

**Comment by dalehenrich** [comment]
source diff from client:
```

diff --git a/rowan/src/Rowan-GemStone-Kernel/Behavior.extension.st b/rowan/src/Rowan-GemStone-Kernel/Behavior.extension.st
index 123a6df..6aa1c31 100644
--- a/rowan/src/Rowan-GemStone-Kernel/Behavior.extension.st
+++ b/rowan/src/Rowan-GemStone-Kernel/Behavior.extension.st
@@ -115,11 +115,44 @@ offset := ivInfo at: 1 .
 ].
 false ifTrue: [ self isModifiable ifFalse:[ ^ self validateIsModifiable ] ].
 mySubclasses := self subclasses .
-mySubclasses do:[:x|
+false ifTrue: [mySubclasses do:[:x|
   (x _validateNewInheritedConstraint:aClass atOffset:offset) ifFalse:[ ^ nil ]
-] .
-self _newConstraint: aClass atOffset: offset .
-mySubclasses do:[:x| x _newInheritedConstraint: aClass atOffset: offset ] .
+] ].
+self _rwNewConstraint: aClass atOffset: offset .
+mySubclasses do:[:x| x _rwNewInheritedConstraint: aClass atOffset: offset ] .
+
+]
+
+{ #category : '*rowan-gemstone-kernel' }
+Behavior >> _rwNewConstraint: aClass atOffset: offset [
+
+	| oldConstraintsArray newConstraintsArray constraintsIndex instanceVariableNames |
+	oldConstraintsArray := self _constraints.
+	newConstraintsArray := oldConstraintsArray copy.
+	instanceVariableNames := self class allInstVarNames.
+	constraintsIndex := instanceVariableNames indexOf: #constraints.
+	self _unsafeAt: constraintsIndex put: newConstraintsArray.
+
+	self _newConstraint: aClass atOffset: offset.
+
+	self _constraints immediateInvariant
+
+]
+
+{ #category : '*rowan-gemstone-kernel' }
+Behavior >> _rwNewInheritedConstraint: aClass atOffset: offset [
+
+"Change the constraint for offset to aClass if that offset is not
+ already constrained to be a subclass of aClass.  Assume all
+ variance and error checks have been done."
+
+self _validatePrivilege ifTrue:[ 
+  ((self _constraintAt: offset ) isSubclassOf: aClass ) ifFalse:[
+    self _rwNewConstraint: aClass atOffset: offset .
+    self subclasses do:[:aSubcls|
+       aSubcls _rwNewInheritedConstraint: aClass atOffset: offset ].
+  ] .
+]
 
 ]
 
diff --git a/rowan/src/Rowan-GemStone-Loader/RwGsClassConstraintsSymDictPatch.class.st b/rowan/src/Rowan-GemStone-Loader/RwGsClassConstraintsSymDictPatch.class.st
index fff521f..2b66b23 100644
--- a/rowan/src/Rowan-GemStone-Loader/RwGsClassConstraintsSymDictPatch.class.st
+++ b/rowan/src/Rowan-GemStone-Loader/RwGsClassConstraintsSymDictPatch.class.st
@@ -58,7 +58,7 @@ RwGsClassConstraintsSymDictPatch >> installPropertiesPatchFor: aPatchSet [
 			ifFalse: [ theVaryingConstraint := arrayOrVaryingConstraintClass ] ].
 	keys := existingConstraintsMap keys copy.
 	keys addAll: theConstraintsMap keys.
-	self _installMutableConstraintsArrayFor: existingClass.
+	false ifTrue: [ self _installMutableConstraintsArrayFor: existingClass ].
 	keys do: [:key | 
 		| existingConstraint theConstraint |
 		existingConstraint := existingConstraintsMap at: key ifAbsent: [].
@@ -83,7 +83,7 @@ RwGsClassConstraintsSymDictPatch >> installPropertiesPatchFor: aPatchSet [
 		ifFalse: [
 			"change the varying constraint"
 			existingClass _setVaryingConstraint: theVaryingConstraint ].
-	self _makeConstraintsArrayInvariantFor: existingClass.
+	false ifTrue: [ self _makeConstraintsArrayInvariantFor: existingClass ].
 	self symbolDictionaryRegistry updateClassProperties: existingClass implementationClass: RwGsSymbolDictionaryRegistry_Implementation.
 
 ]
```
