### ISSUE TITLE
Error on adding a package: lookup fail on project name

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#256]
Customer reports HR 9862, and I verified, that adding a package using jadeite fails. To reproduce: 
start with empty stone, install Rowan, login as SystemUser to clone and load RowanSample1, and make RowanSample1 the default. Then in Jadeite, try to add a package.  

The problem is that createPackage calls createProjectNamed:, which ultimately checks to see if the project exists by doing (Rowan projectNames includes: projectName), but Rowan projectNames returns an IdentitySet, and the string argument that comes from the defaultProjectName is not the same instance of String... so it tries to create the project, which fails since a project with that name does already exist.   

I edited RowanProjectService >> createProjectNamed:in: to change
  (Rowan projectNames includes: projectName)
to be
  (Rowan projectNames asArray includes: projectName) 

and this allow package creation to complete but I doubt this is the real fix...

--------------------

a UserDefinedError occurred (error 2318), reason:halt, internal error - unexpected non-empty project properties modification. See Issue #180

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsImagePatchVisitor (Object) >> error: @6 line 7
RwGsImagePatchVisitor >> visitProjectModification: @22 line 19
RwProjectModification >> acceptVisitor: @2 line 3
[] in  ExecBlock1 (RwGsImagePatchVisitor) >> visitProjecteSetModification: @2 line 4
Dictionary >> do: @8 line 12
RwGsImagePatchVisitor >> visitProjecteSetModification: @3 line 4
RwProjectSetModification >> acceptVisitor: @2 line 3
RwGsImagePatchVisitor >> visit: @2 line 3
RwGsImage class >> applyModification:visitorClass:instanceMigrator: @4 line 5
RwGsImage class >> applyModification:instanceMigrator: @8 line 13
RwPrjLoadTool >> _loadProjectSetDefinition:instanceMigrator: @17 line 19
[] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @3 line 7
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
RwPrjLoadTool >> loadProjectDefinition: @5 line 7
RwPrjBrowserTool >> createGitPackageProjectNamed:updateDefinition: @7 line 7
RowanProjectService >> createProjectNamed:in: @7 line 5
RowanProjectService >> createProjectNamed: @3 line 3
RowanPackageService >> createPackage @6 line 5
JadeServer64bit32 (JadeServer) >> sbAddPackage: @8 line 6
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @21 line 9
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
Should be getting an array of project names, now
