### ISSUE TITLE
Want to develop Rowan code in Rowan

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#27]
Currently, for example, RowanPackageDefinitionService is in the Rowan-Services category. If I want to compile a method, I have to turn off the rwCompileMethod* hooks and compile the traditional way. 

I want to be able to compile every method and class using a rowan api. To get there, we need to: 

- [x] Get minimally functional GS Jade in Dolphin working (package,class, category, method add/remove)
- [x] Switch to Rowan API for Save of Project and Packages (save/load projects & packages)
- [x] Tests cannot destroy existing loaded project structure
- [x] Need to start using stock **SymbolDictionary** instead of **RwGsPackageSymbolDictionary** 
- [x] automatic migration (migration options in project spec)
- [x] basic git commands: branches, checkout, push, pull, merge, status available from tools for building workflows
- [ ] changelog?

**Comment by dalehenrich** [comment]
Here's a screen shot of tODE *after* loading Rowan using Rowan (all the Rowan globals have been moved to `RowanGlobals`) ... on the right the underlined classes have extensions methods ...:

![image](https://user-images.githubusercontent.com/623951/38450008-647863c6-39cb-11e8-8eb1-a56904f62a5e.png)

Anyway haven't done any editing yet, but this is a major step towards being able to use Rowan to develop Rowan ...

**Comment by dalehenrich** [comment]
Haha, well when I run the test suite, things don't look so great:
```
92 run, 49 passes, 1 expected defects, 1 failures, 41 errors, 0 unexpected passes
	92 tests
	92 run
	49 passes
	1 expected defects
	1 failures
RwProjectToolTest debug: #testSimpleProject1
	41 errors
RwBrowserToolApiTest debug: #testAddMethod
RwBrowserToolApiTest debug: #testCreateClass
RwBrowserToolApiTest debug: #testDeleteClass
RwBrowserToolApiTest debug: #testDeleteComplicatedClass
RwBrowserToolApiTest debug: #testDeleteComplicatedPackage
RwBrowserToolApiTest debug: #testDeleteGlobalExtensionMethod
RwBrowserToolApiTest debug: #testDeleteMethod
RwBrowserToolApiTest debug: #testDeletePackage
RwBrowserToolApiTest debug: #testLoadFullMultiProjectDefs
RwBrowserToolApiTest debug: #testLoadMultiProjectDefs
RwBrowserToolApiTest debug: #testMoveGlobalExtensionMethods
RwBrowserToolApiTest debug: #testMoveMethod
RwBrowserToolApiTest debug: #testNewClassVersionA
RwBrowserToolApiTest debug: #testNewClassVersionB
RwEditToolTest debug: #testAddAndRemoveClass
RwEditToolTest debug: #testAddClassExtension
RwEditToolTest debug: #testAddUpdateAndRemoveClass
RwEditToolTest debug: #testUpdateClass
RwEditToolTest debug: #testUpdateClassExtension
RwHybridBrowserToolTest debug: #testHybridClassCreation
RwHybridBrowserToolTest debug: #testHybridClassCreationWithClassCreationTemplateA
RwHybridBrowserToolTest debug: #testHybridClassCreationWithClassCreationTemplateB
RwHybridBrowserToolTest debug: #testHybridCompileMethod
RwHybridBrowserToolTest debug: #testHybridCompileMethodRemove
RwHybridBrowserToolTest debug: #testHybridComplicatedProjectLoad
RwHybridBrowserToolTest debug: #testHybridDeletePackage
RwHybridBrowserToolTest debug: #testHybridMoveClassToPackage
RwHybridBrowserToolTest debug: #testHybridMoveClassToPackageWithClassModifications
RwHybridBrowserToolTest debug: #testHybridNewClassVersionWithSubclassesA
RwHybridBrowserToolTest debug: #testHybridNewClassVersionWithSubclassesAndMethodsA
RwHybridBrowserToolTest debug: #testHybridNewClassVersionWithSubclassesAndMethodsB
RwHybridBrowserToolTest debug: #testHybridNewClassVersionWithSubclassesAndMethodsC
RwHybridBrowserToolTest debug: #testHybridNewClassVersionWithSubclassesB
RwHybridBrowserToolTest debug: #testHybridPackagePatch
RwHybridBrowserToolTest debug: #testHybridProjectLoad
RwProjectSetTest debug: #testProjectSetLoad1
RwProjectToolTest debug: #testProjectClassExtensions
RwProjectToolTest debug: #testProjectClassExtensionsInSeparateSymbolDictionary
RwProjectToolTest debug: #testProjectClassExtensionsInSeparateSymbolDictionaryTheRightWay
RwProjectToolTest debug: #testProjectClassExtensionsInSessionMethods
RwProjectToolTest debug: #testProjectGlobalsClassesExtensionsInSessionMethods
	0 unexpected passes
```

**Comment by dalehenrich** [comment]
... at least half of the tests are passing:)

**Comment by dalehenrich** [comment]
I think the issue I am fighting right now (failing tests) is that there are copies of the classes in UserGlobals and the new classes are installed in RowanGlobals ... I can't load into UserGlobals because it does not have the right SymbolDictionary class ... probably need to add the Rowan project metadata to UserGlobals (or whichever is the target symbol dictionary for installing classes)...

**Comment by dalehenrich** [comment]
With commit e3ab944 all the Rowan tests are passing after boot strapping Rowan using Rowan:
```
92 run, 91 passes, 1 expected defects, 0 failures, 0 errors, 0 unexpected passes
```

**Comment by dalehenrich** [comment]
@ericwinger it looks like changelog is the only unimplemented feature from the original check list that remains unchecked ... i'm just making a pass through the open issues and closing those that can be closed, so it's up to yo whether or  not changelog is still on the list or not ...

**Comment by ericwinger** [comment]
I believe the change log is implemented now. Let's open a new issue if that is not what is desired.
