### ISSUE TITLE
Add/Remove method category in Rowan? 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#28]
The RwPrjBrowserTool doesn't seem to have any api's for adding or removing method categories (that I can find). 

What are the api methods?

**Comment by dalehenrich** [comment]
for now just use the Behavior-based methods for adding protocol .. at the moment, Rowan/Tonel does not record empty method protocol ... I'm not even sure it is allowed in Tonel (definitely not in FileTree).

The protocol is not recorded by Rowan until you add a method ... so no change is needed for GsJade ...

**Comment by ericwinger** [comment]
Ok, I'll close the issue.

**Comment by dalehenrich** [comment]
If it is not possible to remove a non-empty method protocol (and even then we only care about how the methods are removed) then there is no need for Rowan-specific add/remove protocol, since Rowan is not aware of empty protocols ...

**Comment by ericwinger** [comment]
Looks like `JadeServer>>sbRemoveMethodCategories:` sends `Behavior>>removeCategory:environmentId:`
From a non-changed package, remove a method category with methods then do a Show Changes on the package. Instead of seeing the removed methods you'll see no changes. 

Reassigning to @dalehenrich for creation of the rowan category removal.

**Comment by dalehenrich** [comment]
So my paranoia was justified:) Cool!

**Comment by dalehenrich** [comment]
bounce  to @ericwinger for integration into Jadeite
