### ISSUE TITLE
packageName: (NONE) causes class compilation error

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#29]
Per this morning's discussion, classes that are not in Rowan now should have a class creation template with '(NONE)' in the package name. However this doesn't compile, making it difficult to do development. 

RowanDefinitionService rwSubclass: 'RowanClassDefinitionService'
	instVarNames: #( name comment instVarNames
	                  classVarNames classInstVarNames superclassName subclassType
	                  poolDictionaryNames classType packageService meta)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'Rowan-Services'
	packageName: '(NONE)'
	options: #()

a UserDefinedError occurred (error 2318), reason:halt, No package named '(NONE)' found
UserDefinedError (AbstractException) >> _signalWith: @6 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwPrjBrowserTool (Object) >> error: @6 line 7
[] in RwPrjBrowserTool >> addOrUpdateClassDefinition:type:superclass:instVarNames:classVars:classInstVars:poolDictionaries:category:packageName:options: @29 line 6
RwGsImage class >> loadedPackageNamed:ifAbsent: @5 line 11
RwPrjBrowserTool >> _loadedPackageNamed:ifAbsent: @3 line 3
RwPrjBrowserTool >> addOrUpdateClassDefinition:type:superclass:instVarNames:classVars:classInstVars:poolDictionaries:category:packageName:options: @3 line 5
RowanDefinitionService class (Class) >> rwSubclass:instVarNames:classVars:classInstVars:poolDictionaries:category:packageName:options: @6 line 4
Executed Code  @2 line 1
GsNMethod >> _executeInContext: @1 line 1
String >> evaluate @5 line 9
JadeServer64bit34 (JadeServer) >> sbClass: @5 line 5
JadeServer64bit34 (JadeServer) >> systemBrowserCommand @74 line 24
[] in JadeServer >> systemBrowserA: @23 line 10
Time class >> secondsElapsedTime: @6 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit34 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserA: @3 line 4
JadeServer64bit34 (JadeServer) >> systemBrowser: @3 line 2
[] in JadeServer64bit >> systemBrowser: @7 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit) >> systemBrowser: @3 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
ah yes:) good point ... I'll put together a patch for this one shortly ...

**Comment by dalehenrich** [comment]
**Note** that at the moment the proposed fix is not on the main branch ... I've been doing some work that's been isolated in a separate branch ... I'll merge the code to the `master` branch in  a couple more minutes ...

**Comment by ericwinger** [comment]
I'll wait to update until tomorrow.

**Comment by dalehenrich** [comment]
fix merged to master
