### ISSUE TITLE
definition based equivalents to loadedProjects and loadedPackages

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#30]
In order to see the list of loadedProjects & loadedPackages, I iterated over
```
Rowan image loadedProjects
 ``` 
 then sending

 ```
 loadedPackages
 ``` 
to each project. 

I shouldn't be doing this. Instead, I should use a tool to get those lists. What is that api? 

I couldn't find it in 

```
RwPrjBrowserTool
```
nor the definition classes. You may have told me but I can't remember if you did.

**Comment by dalehenrich** [comment]
`Rowan>>projectNames` and `Rowan>>packageNames` is the approved way (now) to get the list of projects and packages in Rowan ... also not on the master branch yet ...

we can talk this over a little bit if you think it should be moved under tools like everything else ... the Rowan class has been a little schizo with what shows up there and as I've mentioned before I don't like exposing loaded things so I will probable end up moving some of those things from **Rowan** ... most of those load* methods pre-date my concerns about exposing loaded things

**Comment by dalehenrich** [comment]
fix merged to master

**Comment by ericwinger** [comment]
Yeah, I'm happy to discuss. 

If we want to avoid exposing loaded packages, then what should we call the list of packages that the user sees?
