### ISSUE TITLE
can't push to git

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#311]
I committed a number of changes to local rowan, but got this error when trying to push to github. That's left me with work that isn't backed up on my local disk. 

a UserDefinedError occurred (error 2318), reason:halt, performOnServer: 'set -e; cd $ROWAN_PROJECTS_HOME/Rowan; git --git-dir $ROWAN_PROJECTS_HOME/Rowan/.git --work-tree $ROWAN_PROJECTS_HOME/Rowan push origin eric' stdout: 'To git@github.com:dalehenrich/Rowan.git
 ! [rejected]        eric -> eric (fetch first)
error: failed to push some refs to ''git@github.com:dalehenrich/Rowan.git''
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., ''git pull ...'') before pushing again.
hint: See the ''Note about fast-forwards'' in ''git push --help'' for details.
' failed with status: 256 errno: 0 errStr: nil

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwGitTool >> performGitCommand:in:worktree:with:logging: @13 line 9
RwGitTool >> performGitCommand:in:with: @2 line 4
RwGitTool >> gitpushIn:with: @2 line 3
RwGitTool >> gitpushIn:remote:branch: @4 line 3
RowanProjectService >> pushToGit @8 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by ericwinger** [comment]
I don't trust the pull to not wipe out all my work from today so I'll wait until you're available to walk me through the recovery.

**Comment by dalehenrich** [comment]
This is not a recovery situation ... it is an everyday occurrence when working in a multi-person repository ...  Your commits are safe and doing a pull from your own branch is safe ... but if you choose to wait, that's your decision ... I should be in the office tomorrow after my (expected) skype call
