### ISSUE TITLE
Can't commit work

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#314]
I have no idea what state my image is in now. The methods changed outside of the services package should be whitespace only. 

![image](https://user-images.githubusercontent.com/36212516/43920395-a8230d1a-9bcd-11e8-9b79-5e24f4853c42.png)

![image](https://user-images.githubusercontent.com/36212516/43920449-c4eb02fe-9bcd-11e8-8fad-dac8aeda8158.png)

![image](https://user-images.githubusercontent.com/36212516/43920476-dccb5d56-9bcd-11e8-883c-f8f6fc8bce8d.png)

**Comment by dalehenrich** [comment]
bug in Oscar...
