### ISSUE TITLE
Unable to load current Oscar

### ISSUE THREAD

**Issue by jgfoster** [dalehenrich/Rowan#321]
I can install a07eb4e741c70929e23467820cb2d47ee384750a but not 998c984aa1678c0bba3f0ee17f0b5284764bdcfd.

Reading /Users/jfoster/Rowan/rowan/src/Rowan-Url-Core/RwTonelUrl.class.st
Notice: a CypressAddition(add: a CypressMethodDefinition(Rowan class>>serviceClasses)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
Notice: a CypressAddition(add: a CypressMethodDefinition(Rowan class>>jadeServerClassNamed:)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
ERROR 2710 , a CypressAddition(add: a CypressMethodDefinition(Rowan class>>serviceClasses)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor (CypressLoaderError)
topaz > exec iferr 1 : stk 
==> 1 CypressLoaderError (AbstractException) >> _signalWith: @5 line 25
2 CypressLoaderError (AbstractException) >> signal @2 line 47
3 CypressLoader >> handlePatchOperation:failure: @3 line 8
4 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 8
5 CompileError (AbstractException) >> _executeOuterHandler: @3 line 7
6 CompileError (AbstractException) >> _pass:with: @4 line 13
7 CompileError (AbstractException) >> pass      @2 line 14
8 CypressLoader >> handleCompileError:from:     @9 line 9
9 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 6
10 CompileError (AbstractException) >> _executeHandler: @3 line 8
11 CompileError (AbstractException) >> _signalWith: @1 line 1
12 CompileError (AbstractException) >> signal    @2 line 47
13 Metaclass3 (Behavior) >> _checkCompileResult:source:suppressCompileWarning: @11 line 21
14 Metaclass3 (Behavior) >> _checkCompileResult:source: @2 line 3
15 Metaclass3 (Behavior) >> compileMethod:dictionaries:category:intoMethodDict:intoCategories:intoPragmas:environmentId: @3 line 34
16 [] in  ExecBlock0 (Behavior) >> compileMethod:dictionaries:category:environmentId: @2 line 37
17 GsObjectSecurityPolicy class >> setCurrent:while: @6 line 7
18 Metaclass3 (Behavior) >> compileMethod:dictionaries:category:environmentId: @15 line 36
19 CypressMethodDefinition >> loadMethodDefinition @7 line 4
20 CypressAddition >> loadMethodDefinition       @3 line 2
21 [] in  ExecBlock0 (CypressLoader) >> loadMethodDefinition: @2 line 4
22 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
23 [] in  ExecBlock0 (CypressLoader) >> loadMethodDefinition: @2 line 5
24 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
25 CypressLoader >> loadMethodDefinition:        @2 line 7
26 [] in  ExecBlock1 (CypressLoader) >> loadAdditions: @2 line 6
27 OrderedCollection (Collection) >> do:         @5 line 10
28 CypressLoader >> loadAdditions:               @3 line 6
29 CypressLoader >> retryFailedLoads             @8 line 12
30 CypressLoader >> load:                        @6 line 5
31 CypressLoader >> load                         @2 line 2
32 CypressPackageManager3 >> loadResolvedReferences @8 line 12
33 [] in  Executed Code                          @10 line 16
34 Executed Code                                 @2 line 2
35 GsNMethod class >> _gsReturnToC               @1 line 1
topaz > exec iferr 2 : stack 
==> 1 CypressLoaderError (AbstractException) >> _signalWith: @5 line 25
    receiver a CypressAddition(add: a CypressMethodDefinition(Rowan class>>serviceClasses)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    inCextensionArg nil
    res nil
(skipped 1 evaluationTemps)
2 CypressLoaderError (AbstractException) >> signal @2 line 47
    receiver a CypressAddition(add: a CypressMethodDefinition(Rowan class>>serviceClasses)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
(skipped 2 evaluationTemps)
3 CypressLoader >> handlePatchOperation:failure: @3 line 8
    receiver aCypressLoader
    aPatchOperation aCypressAddition
    anException a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
(skipped 1 evaluationTemps)
4 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 8
    self aCypressLoader
    receiver anExecBlock1
    ex a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aPatchOperation aCypressAddition
    self aCypressLoader
(skipped 4 evaluationTemps)
5 CompileError (AbstractException) >> _executeOuterHandler: @3 line 7
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aBlock anExecBlock1
(skipped 4 evaluationTemps)
6 CompileError (AbstractException) >> _pass:with: @4 line 13
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aHandler anExecBlock1
    isNonStaticAnsi true
(skipped 3 evaluationTemps)
7 CompileError (AbstractException) >> pass      @2 line 14
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
(skipped 4 evaluationTemps)
8 CypressLoader >> handleCompileError:from:     @9 line 9
    receiver aCypressLoader
    aCompileError a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aPatchOperation aCypressAddition
    self aCypressLoader
    otherErrors anArray
    undefinedSymbolErrors anArray
(skipped 1 evaluationTemps)
9 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 6
    self aCypressLoader
    receiver anExecBlock1
    ex a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aPatchOperation aCypressAddition
    self aCypressLoader
(skipped 4 evaluationTemps)
10 CompileError (AbstractException) >> _executeHandler: @3 line 8
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    aBlock anExecBlock1
    res nil
(skipped 2 evaluationTemps)
11 CompileError (AbstractException) >> _signalWith: @1 line 1
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
    inCextensionArg nil
12 CompileError (AbstractException) >> signal    @2 line 47
    receiver a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
(skipped 2 evaluationTemps)
13 Metaclass3 (Behavior) >> _checkCompileResult:source:suppressCompileWarning: @11 line 21
    receiver Rowan class
    result anArray
    sourceString serviceClasses

	| array |
	array := Array with: RowanService. 
	array addAll: RowanService allSubclasses.
	^array
    suppressCompileWarning false
    meth nil
    warnStr nil
    errorArray anArray
(skipped 2 evaluationTemps)

**Comment by ericwinger** [comment]
@jgfoster The workspace at the bottom looks like code that I'm working on in Rowan to be able to login as DataCurator. (fyi - I changed that code since you submitted this issue) 

Who are you trying to login in as? -- Right now, I wouldn't expect anyone but SystemUser to login and be fully functional.

**Comment by jgfoster** [comment]
Discussion moved to https://github.com/ericwinger/Jade/issues/32.
