### ISSUE TITLE
Installing rowan oscar branch fails with 0bfe73e

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#327]
I usually update but wonked my image with removing a package.
Rebuilding rowan with an empty extent using standard install script errors.
Suspicious JadeServer refs...

-snip-
topaz 1> 
topaz 1> # Define the classes needed by definitions, configurations and specifications
topaz 1>   run
  CypressBootstrapRowanBlock 
    value: 'RowanKernel'
    value: #('Rowan-Kernel' 'Rowan-Url-Core').
%
ERROR 2710 , a CypressAddition(add: a CypressMethodDefinition(Rowan class>>jadeServerClassNamed:)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor (CypressLoaderError)
topaz > exec iferr 1 : stk 
==> 1 CypressLoaderError (AbstractException) >> _signalWith: @5 line 25
2 CypressLoaderError (AbstractException) >> signal @2 line 47
3 CypressLoader >> handlePatchOperation:failure: @3 line 8
4 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 8
5 CompileError (AbstractException) >> _executeOuterHandler: @3 line 7
6 CompileError (AbstractException) >> _pass:with: @4 line 13
7 CompileError (AbstractException) >> pass      @2 line 14
8 CypressLoader >> handleCompileError:from:     @9 line 9
9 [] in  ExecBlock1 (CypressLoader) >> loadMethodDefinition: @2 line 6
10 CompileError (AbstractException) >> _executeHandler: @3 line 8
11 CompileError (AbstractException) >> _signalWith: @1 line 1
12 CompileError (AbstractException) >> signal    @2 line 47
13 Metaclass3 (Behavior) >> _checkCompileResult:source:suppressCompileWarning: @11 line 21
14 Metaclass3 (Behavior) >> _checkCompileResult:source: @2 line 3
15 Metaclass3 (Behavior) >> compileMethod:dictionaries:category:intoMethodDict:intoCategories:intoPragmas:environmentId: @3 line 34
16 [] in  ExecBlock0 (Behavior) >> compileMethod:dictionaries:category:environmentId: @2 line 37
17 GsObjectSecurityPolicy class >> setCurrent:while: @6 line 7
18 Metaclass3 (Behavior) >> compileMethod:dictionaries:category:environmentId: @15 line 36
19 CypressMethodDefinition >> loadMethodDefinition @7 line 4
20 CypressAddition >> loadMethodDefinition       @3 line 2
21 [] in  ExecBlock0 (CypressLoader) >> loadMethodDefinition: @2 line 4
22 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
23 [] in  ExecBlock0 (CypressLoader) >> loadMethodDefinition: @2 line 5
24 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
25 CypressLoader >> loadMethodDefinition:        @2 line 7
26 [] in  ExecBlock1 (CypressLoader) >> loadAdditions: @2 line 6
27 OrderedCollection (Collection) >> do:         @5 line 10
28 CypressLoader >> loadAdditions:               @3 line 6
29 CypressLoader >> retryFailedLoads             @8 line 12
30 CypressLoader >> load:                        @6 line 5
31 CypressLoader >> load                         @2 line 2
32 CypressPackageManager3 >> loadResolvedReferences @8 line 12
33 [] in  Executed Code                          @10 line 16
34 Executed Code                                 @2 line 2
35 GsNMethod class >> _gsReturnToC               @1 line 1
topaz > exec iferr 2 : stack 
==> 1 CypressLoaderError (AbstractException) >> _signalWith: @5 line 25
    receiver a CypressLoaderError
      gsResumable         true
      gsTrappable         true
      gsNumber            2710
      currGsHandler       nil
      gsStack             nil
      gsReason            nil
      gsDetails           nil
      tag                 nil
      messageText         a CypressAddition(add: a CypressMethodDefinition(Rowan class>>jadeServerClassNamed:)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
      gsArgs              nil
      exception           a CompileError
      patchOperation      a CypressAddition
    inCextensionArg nil
    res nil
(skipped 1 evaluationTemps)
2 CypressLoaderError (AbstractException) >> signal @2 line 47
    receiver a CypressLoaderError
      gsResumable         true
      gsTrappable         true
      gsNumber            2710
      currGsHandler       nil
      gsStack             nil
      gsReason            nil
      gsDetails           nil
      tag                 nil
      messageText         a CypressAddition(add: a CypressMethodDefinition(Rowan class>>jadeServerClassNamed:)) failed because a CompileError occurred (error 1001), compilation errors -- parameter 1 is error descriptor
      gsArgs              nil
      exception           a CompileError
      patchOperation      a CypressAddition
(skipped 2 evaluationTemps)

-snip-

13 Metaclass3 (Behavior) >> _checkCompileResult:source:suppressCompileWarning: @11 line 21
    receiver a Metaclass3
      superClass          a Metaclass3
      format              16778768
      instVarsInfo        1125900057837588
      instVarNames        a Array
      constraints         a Array
      classVars           nil
      methDicts           a GsMethodDictionary
      poolDictionaries nil
      categorys           a GsMethodDictionary
      primaryCopy         nil
      name                nil
      classHistory        nil
      transientMethDicts a Array
      destClass           a metaRowan
    result a Array
      #1 nil
      #2 a Array
      #3 nil
    sourceString jadeServerClassNamed: className

        | jadeClasses |
        jadeClasses := Array with: JadeServer. 
        jadeClasses add: JadeServer64bit32. 
        ^jadeClasses detect:[:cls | cls name == className] ifNone:[self error: 'Could not look up a JadeServer class: ', className]
    suppressCompileWarning false
    meth nil
    warnStr nil
    errorArray a Array
      #1 a Array
      #2 a Array
-snip-

**Comment by ericwinger** [comment]
Was referencing JadeServer classes directly. Just looked up the symbols in UserGlobals temporarily.
