### ISSUE TITLE
Security error when opening `project list` and `project browser` as user without write permissions to UserGlobals

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#342]
Missed both these cases today when fixing #340 ... although neither of these are expected to be used in the target use case ... nonetheless worth fixing for the future.

Here's the stack:
```
a SecurityError occurred (error 2116), An attempt was made to modify the object aSymbolDictionary( #'UserGlobals'->aSymbolDictionary, #'GsPackagePolicy_Current'->aGsPackagePolicy) in objectSecurityPolicyId 11 with insufficient authorization.
---
SecurityError (AbstractException) >> _signalFromPrimitive: @5 line 15
SymbolDictionary (AbstractDictionary) >> _atZ:putKey:value: @1 line 1
SymbolDictionary (IdentityKeyValueDictionary) >> _at:put: @17 line 13
SymbolDictionary >> _at:put: @4 line 4
SymbolDictionary >> at:put: @9 line 12
[] in  ExecBlock0 (RwGsImage class) >> _loadedProjectRegistryForUserId: @7 line 15
SymbolDictionary >> at:ifAbsent: @12 line 18
RwGsImage class >> _loadedProjectRegistryForUserId: @10 line 11
RwGsImage class >> loadedProjects @3 line 6
RwGsImage class >> projectNames @2 line 5
Rowan class >> projectNames @3 line 5
RowanProjectService >> projects @2 line 3
GsNMethod class >> _gsReturnToC @1 line 1
```
Spots of `UserGlobal` interest (based on code inspection):
- [x] `RwGsImage class>>_loadedProjectRegistryForUserId:`. Source of stack.
- [ ] `RowanServicePreferences class>>current`. Potential problem if not dead code.
- [x] `RwPlatform class>>reset`. Needs to match `RwPlatform class>>current`.
- [x] `RwGsPlatform>>jadeServerClassNamed:`. Hardwired references to `UserGlobals` actually makes this case safe, but will not survive if/when the `JadeServer` classes are moved.

**Comment by dalehenrich** [comment]
Added `RwPlatform class>>_userPlatformDictionary` to return either `UserGlobals` or `SessionTemps current` depending upon whether or not user has write permission on `UserGlobals`.

**Comment by dalehenrich** [comment]
bounce to @ericwinger to take care of `RowanServicePreferences class>>current' ...

**Comment by dalehenrich** [comment]
@ericwinger my bugfix (needed for yours) is now on the candidateV1.1 branch

**Comment by ericwinger** [comment]
Fix in https://github.com/ericwinger/Jade/issues/96
