### ISSUE TITLE
project list window

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#37]
This is an example of the menu items from the tODE project list:

![image](https://user-images.githubusercontent.com/623951/38146339-6bbd9026-3402-11e8-844c-a6a13f0e6423.png)

We need to have a subset of this functionality for the `hybrid browser`

**Comment by ericwinger** [comment]
This is a nice list of project tools for the pilot release. 

	#('changes' nil #'diffMenuAction:selectionIndex:').
	#('load' nil #'loadProjectMenuAction:selectionIndex:').
	#('log' nil #'commitLogMenuAction:selectionIndex:').
	#('push' nil #'gitPushProjectMenuAction:selectionIndex:').
	#('revert' nil #'revertProjectMenuAction:selectionIndex:').
#('save' nil #'commitProjectMenuAction:selectionIndex:').

**Comment by ericwinger** [comment]
Update: I have write, commit, changes, clone working simplistically.

**Comment by ericwinger** [comment]
Pretty sure that this can be closed now. Project List alpha functionality is mostly complete.
