### ISSUE TITLE
Running test out of the box fails

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#4]
After successfully loading Rowan I tried to run a random test, RwLoadingTest>>testMethodDelete. 
However, it failed with this stack. The configuration instance variable is nil. That implies some missing
setup is needed to run the tests. 

```
MessageNotUnderstood >> defaultAction @4 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @10 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @8 line 13
Rowan class >> updateLoadedPackages @3 line 9
Rowan class >> loadedPackagesNamed: @3 line 10
Rowan class >> loadedPackageDefinitionsNamed: @2 line 6
RwLoadingTest >> loadAndTestPackagesNamed:loaded:using: @5 line 7
RwLoadingTest >> loadAndTestPackagesNamed:using: @2 line 3
RwLoadingTest >> testMethodDelete @13 line 20
RwLoadingTest (Object) >> perform: @1 line 1
RwLoadingTest (TestCase) >> performTest @3 line 2
[] in TestCase >> runCase @14 line 5
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwLoadingTest (TestCase) >> runCase @5 line 6
[] in TestCase >> debug @9 line 2
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwLoadingTest (TestCase) >> debug @3 line 3
RwLoadingTest class (TestCase class) >> debug: @3 line 3
[] in JadeServer >> sbRunMethodTests: @14 line 6
Array (Collection) >> do: @6 line 10
JadeServer64bit34 (JadeServer) >> sbRunMethodTests: @9 line 6
"rowanTestStack.st" [dos] 24L, 1251C                          1,1           Top

```

**Comment by dalehenrich** [comment]
```Smalltalk
Rowan initialize.
```
Should repair that problem ... odd that the initialize method did not get run, that should have been done during package loads... There's a possibility that my work has broken the package structure and/or initializers --- related to the fact that the load code does not fail when an error occurs during the load ... I'm chasing a real test failure at the moment before I turn into a pumpkin and have to start cooking dinner  ...

**Comment by dalehenrich** [comment]
@ericwinger is this a show stopper for you? If it is I'm at a point where I can work on the installation process... otherwise, I will continue moving toward completing the browse tool api

**Comment by ericwinger** [comment]
Nope. I’m connected to the repository and developing.  I just ran the #initialize by hand. 


Eric Winger
eric@thewingers.net
503.516.6271


Awards:
* 2017 District 7 Toastmasters Table Topics (impromptu speaking) Champion
* 2017 Black Belt - Chung Kuo Chuan Martial Arts
* 2016 Distinguished Toastmaster
* Winner of the 2013/14 Herb C. Stude Award for Educational Excellence
* 2014 District 7 Toastmasters Evaluation Contest Champion
* 2012 District 7 Toastmasters Humorous Speech Contest Champion

Current Volunteering:
* Little Toasties youth speaking club coach 2016 - Present
* Silicon Forest Toastmasters President 2017/18

Speech Coach - ericwinger.net
Speech Teacher - MIT School
Engineer - GemTalk Systems

**Comment by dalehenrich** [comment]
As confirmed by [this comment](https://github.com/dalehenrich/Rowan/issues/6#issuecomment-371682068), there were errors during the Rowan installation that were "ignored" by the install script ... closing this issue in favor of Issue #6
