### ISSUE TITLE
How to know if a project exists on disk? 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#42]
What is the api for determining if a project exists on disk? 

Basically, I'd like to know what information has to be present in order for this command to work: 
```
^(Rowan projectTools diff diffSpecUrl: name) asString.
```

I suppose it would be good to know the api's for setting that information as well.

**Comment by ericwinger** [comment]
First thought. You may wish to update the readme with the preferred api. 
```
^Rowan projectTools diff diffForProjectName: projectName
```

**Comment by ericwinger** [comment]
I'm leery of deleting all the projects in my image with the suggested code until I get my changes checked in. As noted in the other bug comments, there may be a mismatch between what is in my image and what I have checked out on disk. 

After that is resolved, let's discuss the disk project methods you mentioned.

**Comment by ericwinger** [comment]
I've reviewed the two methods you mentioned.  While I now agree that creating projects through the GS_Jade interface should always create a project on disk, it's not clear to me why this api should require a project definition. 

The other api's, so far, have always been name based. 

Thoughts?

**Comment by dalehenrich** [comment]
@ericwinger, the readme is intended to document how you install and work with the Rowan project itself and as you may recall Rowan is managed differently than regular Rowan projects --- when Rowan is managed by Rowan, there won't be any confusion (and the readme will be updated) but we need to get the Pilot GUI to the point where it can be used to develop Rowan ...

If a name-based api is missing or used in an example then it is a hole in the api ...  I can't tell whether you other comments were written before or after we talked (presumably before) ... 

the r`oot path` refers to the root directory of the git project, while  the `repo path` refers to the directory in which the packages are written...

**Comment by dalehenrich** [comment]
I'm not sure which "two methods" you are talking about ... I think I mentioned 4 or 5 methods ...

**Comment by dalehenrich** [comment]
... also I mentioned that we should review some of those methods together ... I imagine that I knew that they weren't exactly what we needed, but figured that when we got together I could better understand your requirements  .... we can talk again tomorrow morning ... I happened to have added some new project functionality (downloading specs use https: protocol that is only available in tODE), as an example of the way that I expect folks to reference github projects ... I plan to add a new project example for the tODE `prj list` and if I get it done tonight, we'll have a name-based api for creating a project ...

**Comment by dalehenrich** [comment]
I think that this issue is no longer relevant ... we've made several decisions in the last two weeks ...
