### ISSUE TITLE
RwGsPackageSymbolDictionary class is going away ... Rowan-Services has one reference

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#53]
[RowanService>>createSymbolDictionaryNamed:](https://github.com/dalehenrich/Rowan/blob/master/src/tonel/Rowan-Services/RowanService.class.st#L47-L56) is the method with a reference to **RwGsPackageSymbolDictionary**.  Once I've merged the issue_27 branch into master, you'll be able to create a regular SymbolDictionary in this method and the SymbolDictionary will be *rowanized* when it is used. 

Let's talk on Monday about the best way to do this:
1. I can write the replacement code (at the risk of getting a merge conflict when I merge issue_27 branch,
2. You can change your code to lookup the class and when it no longer exists, use **SymbolDictionary**
3. ???

I'll probably go with option 1 over the weekend since I expect to get the new **SymbolDictionary** code working today and I want the class to be gone at least while I am getting things working ...

**Comment by ericwinger** [comment]
Fixed some time ago.
