### ISSUE TITLE
apparent Dolphin error loading Rowan into 3.2.15 (SystemUser) using Jadeite ....

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#56]
Click on the `Rowan packages` button, I get an error(?) that looks like the following:
![image](https://user-images.githubusercontent.com/623951/38595535-3eacada8-3d01-11e8-9d67-1ef9518951f8.png)
... loaded things looks correct when inspecting project and package/class/method registry... 

Here's what appears to be a stack trace:

[Rowan.txt](https://github.com/dalehenrich/Rowan/files/1897228/Rowan.txt)

**Comment by ericwinger** [comment]
Unfortunately, I can't reproduce this. So it may be something about how you opened the system browser shown in the picture. Questions: 

- Is the bug reproduceable from a fresh System Browser (Ctrl-B on the Jade Transcript window)? 
- How did you open the system browser where the problem occurred? 
- If it is intermittent, does selecting or deselecting dictionaries make a difference before clicking Rowan Packages? 
- The session number is 5.  That implies this image may have had multiple logins. Is it possible that this system browser is from another session and did not get closed properly on a prior logout?

**Comment by dalehenrich** [comment]
I cannot run jade.exe against 3.4.0 and I haven't given you you the instructions for running against 3.2.15 as SystemUser, so I didn't think that you would be able to reproduce the problem without more instructions from me. 

What does the error mean ... the stack means nothing to me, so I assume that it is some sort of funky Dolphin error. I was hoping that the stack and error message 'Not found: Package` would mean something to you.

I *am* beginning to wonder if there might be something funky about the fact that I am trying to run against 3.2.15 --- I assume that the `Package` in question is a Dolphin package not a Rowan package, so it isn't likely to be anything directly related to the Rowan code itself... 

The other possibility is that I've neglected to load something that is critical to the Rowan package functionality and the  'Not found: Package` is a *standard error* that is signalled when something inside of the Jade code base breaks...

> Is the bug reproduceable from a fresh System Browser (Ctrl-B on the Jade Transcript window)?

yes

> How did you open the system browser where the problem occurred?

`Ctl-B` and I open the browser **before** I have installed Rowan using the load menu item, because I have to make an edit to the Services code to change the configuration used to do the load ... So the load completes without error and the System Browser seems to be healthy until I click on the tab.

> If it is intermittent, does selecting or deselecting dictionaries make a difference before clicking Rowan Packages?

It is not intermittent.

> The session number is 5. That implies this image may have had multiple logins. Is it possible that this system browser is from another session and did not get closed properly on a prior logout?

I am only running one Jade session at any one time

**Comment by dalehenrich** [comment]
It turns out that simply clicking on the package tab brings up the `Not found: Package` error when I  open the System Browser immediately after logging into the 3.2.15 stone as SystemUser ... so loading Rowan is not involved ... my guess is that the error is coming up, because the package tab is only going to be enabled, when Jade detects that Monticello is installed and it isn't present when logging in as SystemUser ...

In fact, when I run Jaded (and not your "jadeite executable") I get the exact same error ... so this bug exists in Jade and has nothing to do with Rowan or Jadeite...

**Comment by dalehenrich** [comment]
... it does however, prevent me using jadeite to develop Rowan in Rowan (issue #27) :(

**Comment by ericwinger** [comment]
Can you attach a screen shot with more of the window? I need to see what's beneath in particular.

**Comment by dalehenrich** [comment]
![image](https://user-images.githubusercontent.com/623951/38645524-2a821e4c-3d99-11e8-9691-fb6363051a34.png)

**Comment by dalehenrich** [comment]
... the above screen shot was made using a regular `jade.exe`

**Comment by dalehenrich** [comment]
rogue is on the vpn, so you should be able to connect to my `test_rowan_dev_3215` stone if necessary

**Comment by ericwinger** [comment]
Essentially, the problem is that when you click Packages, Jade tries to replace the 'Globals' tab with a 'Package' tab in the pane below. However, it can't find your 'Package' tab for some reason.

**Comment by dalehenrich** [comment]
I  downloaded the new jadeite and I still get `No packages` when clicking on the packages tab, just like with jade ... is it supposed to function differently if I actually have Rowan packages loaded?

**Comment by ericwinger** [comment]
Does the dialog say "No packages" or "Not Found: Package"  as before?

**Comment by dalehenrich** [comment]
"Not found: Package" ... sorry exactly the same error as before

**Comment by dalehenrich** [comment]
Have you not tried this yourself?

**Comment by ericwinger** [comment]
It doesn't reproduce for me. :(

**Comment by dalehenrich** [comment]
Did you tried logging into test_rowan_dev_3215 on rogue as SystemUser?

**Comment by ericwinger** [comment]
That's next. What's the login parms?

**Comment by dalehenrich** [comment]
use `rowan` as gem host name instead of `10.0.0.5` everything else should be the same:
![image](https://user-images.githubusercontent.com/623951/38647548-b2a3c200-3da1-11e8-9eba-22d3dc62e4d0.png)

**Comment by ericwinger** [comment]
ewinger@foos:/foos2/users/ewinger/GsDevKit_home/shared/repos/Rowan$ ping 10.0.0.5
PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
From 70.103.25.42 icmp_seq=1 Destination Net Unreachable
From 70.103.25.42 icmp_seq=2 Destination Net Unreachable

**Comment by ericwinger** [comment]
ewinger@foos:/foos2/users/ewinger/GsDevKit_home/shared/repos/Rowan$ ping 10.0.0.5
PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
From 70.103.25.42 icmp_seq=1 Destination Net Unreachable
From 70.103.25.42 icmp_seq=2 Destination Net Unreachable

**Comment by ericwinger** [comment]
ack... retry. 

```
ping rogue
PING rogue.gemtalksystems.com (10.94.141.71) 56(84) bytes of data.
From foos.gemtalksystems.com (10.94.141.14) icmp_seq=1 Destination Host Unreachable
From foos.gemtalksystems.com (10.94.141.14) icmp_seq=2 Destination Host Unreachable
From foos.gemtalksystems.com (10.94.141.14) icmp_seq=3 Destination Host Unreachable
```

**Comment by dalehenrich** [comment]
sorry I'm on `rogue`

**Comment by dalehenrich** [comment]
did you try logging into one of your own stones using SystemUser?

**Comment by ericwinger** [comment]
Ahhhhhhh ... a reproduction case. :)  Let me work on this.

**Comment by dalehenrich** [comment]
Is it something special about my stone, 3.2.15. something else? enquiring minds are ... um, curious...

**Comment by ericwinger** [comment]
apparently it's SystemUser.  I'm getting nice broken things logged in this way. 

Try using DataCurator and see if you can click on the Rowan Packages tab.

**Comment by dalehenrich** [comment]
... not easy ... the 3.2.15 install script currently does a bunch of changes as System User and installs Rowan as SystemUser ... what happens when you login to test_rowan_dev_3215 as DataCurator?

**Comment by ericwinger** [comment]
Go ahead and try the new executable, Rowan.exe, in /home/ewinger/temp. When I logged in to the foos stone as SystemUser, I found a bug which could account for the behavior you're seeing. 

However, I was unable to progress any farther (as SystemUser) because of the bug below. You may have better luck. 

Observations related to the walkback:
- When I looked at the method, RwGsPlatform>>projectTools method I saw it was an extension method in Rowan-Tools.
- I loaded the Rowan project as DataCurator and am trying to use it as SystemUser
```
a MessageNotUnderstood occurred (error 2010), a RwGsPlatform does not understand  #'projectTools'
MessageNotUnderstood >> defaultAction @3 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
RwGsPlatform (Object) >> doesNotUnderstand: @10 line 10
RwGsPlatform (Object) >> _doesNotUnderstand:args:envId:reason: @8 line 13
Rowan class >> projectTools @3 line 3
RowanClassService (RowanService) >> projectTools @2 line 3
RowanClassService (RowanService) >> browserTool @2 line 3
RowanClassService >> classCreationTemplate @2 line 3
JadeServer64bit34 (JadeServer) >> sbClassTemplate @5 line 4
JadeServer64bit34 (JadeServer) >> sbUpdateClassInfo @5 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserUpdate @7 line 8
JadeServer64bit34 (JadeServer) >> systemBrowserCommand @190 line 62
[] in JadeServer >> systemBrowserA: @23 line 10
Time class >> secondsElapsedTime: @6 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit34 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit34 (JadeServer) >> systemBrowserA: @3 line 4
JadeServer64bit34 (JadeServer) >> systemBrowser: @3 line 2
[] in JadeServer64bit >> systemBrowser: @7 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 44
JadeServer64bit34 (JadeServer64bit) >> systemBrowser: @3 line 5
GsNMethod class >> _gsReturnToC @1 line 1

```

**Comment by ericwinger** [comment]
> ... not easy ... the 3.2.15 install script currently does a bunch of changes as System User and installs Rowan as SystemUser ... what happens when you login to test_rowan_dev_3215 as DataCurator?

I couldn't login because I can't reach rogue.

**Comment by dalehenrich** [comment]
Since you are not reaching rogue and the stones on foos are not running the same code that I'm running on rogue, I'll wait until tomorrow to do any more potentially futile experiments with jadeite ... I don't know how you installed code as SystemUser to get the stack above (or which stone you you were experimenting with), but if you aren't on the gs_3215 branch, I wouldn't expect much of Rowan to work as only two thirds of the tests were passing with 3.2.15 and I've never tried loading things as SystemUser for 3.4.0, but I would not expect much to work there either ...  

I've got plenty of other things I can work on at the moment ...

**Comment by ericwinger** [comment]
Please try the new Rowan.exe in /home/ewinger/temp when you have a chance. Thanks. 

I believe the problem was because, as you noticed, Monticello was installed. If the browser noticed that McWorkingCopy was not present in the server, it forced the dictionary tab to always be selected.

**Comment by dalehenrich** [comment]
Running rowan.exe against a 3.2.15 with Rowan installed as SystemUser using install scripts from commit e2f0982 is now working ... not much testing, but everything is visible in the packages browser as expected
