### ISSUE TITLE
#diffForProjectName: not understood in 3215 rowan

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#58]
Executing this in a gemstone workspace gives a does not understand.

```
Rowan projectTools diff diffForProjectName: 'Rowan'
```

**Comment by dalehenrich** [comment]
This feature depends upon code that currently is only available when tODE is installed (MCDiffy)... will need to port this functionality to Rowan

**Comment by dalehenrich** [comment]
further discussion should take place in #85 ...
