### ISSUE TITLE
rowan build script fails

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#6]
Here is the tail end of running 
./newBuild_rowan 

```
topaz 1> 
topaz 1>   commit
Successful commit
topaz 1> 
topaz 1>   run
  | packageManager repo |
  packageManager := CypressPackageManager3 new.
  repo := CypressAbstractRepository
    onUrl: (CypressUrl absoluteFromText: 'tonel:/foos2/users/ewinger/GsDevKit_home/shared/repos/Rowan/src/tonel/'  )
    alias: ''.
  packageManager
    defaultSymbolDictionaryName: #'UserGlobals'.
  #('Cypress-Core' 'Rowan-Url' 'Rowan-Core' 'Rowan-GemStone' 'Rowan-Cypress' 'Rowan-Tests' 'Rowan-Tode')
    do: [ :packageName | 
      packageManager
        addResolvedReference:
          (CypressResolvedReference name: packageName repository: repo) ].
  packageManager loadResolvedReferences
%
ERROR 2710 , a CypressAddition(add: a CypressMethodDefinition(TDRowanTool class>>initialize)) failed because a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'repositoryTools' (CypressLoaderError)
topaz 1> 
topaz 1>   run
  Rowan addProject: (STON fromString: (GsFile openReadOnServer: '/foos2/users/ewinger/GsDevKit_home/server/stones/test_rowan_340/rowanSpec.ston') contentsOfEntireFile)
%
ERROR 2010 , a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'image' (MessageNotUnderstood)
topaz 1>   commit
Successful commit
topaz 1>   exit
Logging out session 1.
--- 03/08/2018 17:12:06.412 PST Logging out
**Error on or near line 64 :: startTopaz test_rowan_340 -l :: startTopaz test_rowan_340 -l**
ewinger@foos:/foos2/users/ewinger/GsDevKit_home/server/stones/test_rowan_340$

**Comment by dalehenrich** [comment]
Good ... there's the initialize error and the project spec for Rowan 
(which you don't need) is failing it's load ... presumably everything 
else is loading without error ... need to fiddle the topaz scripts and 
figure out the initialization failure ...

Dale

**Comment by ericwinger** [comment]
After running the new build, I realized I forgot to update from git first. But this result was unexpected. 

ewinger@foos:/foos2/users/ewinger/GsDevKit_home/server/stones/test_rowan_340$ git pull origin master
From https://github.com/GsDevKit/GsDevKit_gs_server
 * branch            master     -> FETCH_HEAD
Already up-to-date.
ewinger@foos:/foos2/users/ewinger/GsDevKit_home/server/stones/test_rowan_340$

**Comment by dalehenrich** [comment]
you updated git in the wrong spot ...

```
cd $GS_HOME/shared/repos/Rowan
git pull origin master
```

**Comment by ericwinger** [comment]
How hard would it be to make both of those commands work from the same directory? 

Since I'm for-git-ful and git-nor-ant, it's hard to keep little details like this straight.

**Comment by dalehenrich** [comment]
I would suggest that you create a bash script or alias:
```
pushd $GS_HOME/shared/repos/Rowan
git pull origin master
cd $GS_HOME/server/stones/test_rowan_340
./newBuild_rowan
popd
```

**Comment by ericwinger** [comment]
I've done that. That's useful as long as updating Rowan remains stable.

**Comment by dalehenrich** [comment]
For what definition of `stable`?

**Comment by ericwinger** [comment]
Well, horses live in stables and there is a lot of manure in stables. 
Since I like horses, I'm ok with a few smells. :)

**Comment by dalehenrich** [comment]
When we get to the point where we can use Rowan to update Rowan, there will be a new script for updating an existing stone. 

The `newBuild_rowan` script will be kept around to reload Rowan into a *fresh* image ... so your script should be good until Rowan reaches the point where it no longer relies on tODE and I've created .gs files for bootstrapping Rowan

**Comment by dalehenrich** [comment]
[see this script](https://github.com/dalehenrich/Rowan/issues/10#issuecomment-372465709) for instructions on picking up the updates for this issue
