### ISSUE TITLE
commit not consistent with image

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#62]
Possible bug, 

This showed up in my git commit but did not show up in the rowan diff: 
```
 { #category : 'examples' }
 RowanProjectService >> removeProjectNamed: projectName [ 
 	(Rowan loadedProjectNamed: projectName ifAbsent: [  ])
```
Image method is this. Note the difference. 
```
removeProjectNamed: projectName
        (Rowan loadedProjectNamed: projectName ifAbsent: [  ])
                ifNotNil: [ :project | Rowan image _removeLoadedProject: project ].
```
It's possible that I compiled that method change outside of Rowan before we went to Rowan-in-Rowan. Recording just in case. 

After I found the discrepancy, I tried compiling the method again with a small change. Rowan found that. 

diff code: 
```
(Rowan projectTools diff diffForProjectName: 'Rowan') asString
```

**Comment by dalehenrich** [comment]
Okay ... I'm not sure if there is anything to do here ... it sounds like you figured out that you you probably forgot to hit the "compile in Rowan" button, is that correct?

**Comment by ericwinger** [comment]
Yes, I believe so. I'll close the issue.
