### ISSUE TITLE
Jadeite: should check for nil default project before doing operations that use default project

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#63]
Got the following when I tried adding a package before setting default project:
![image](https://user-images.githubusercontent.com/623951/38748150-105978fc-3f02-11e8-8aff-ab302f9631c8.png)
When I saw that the default project was `nil`, I realized my mistake, but a notification that no default project has been set would be a bit cleaner

**Comment by ericwinger** [comment]
Yes, a friendly dialog would be much nicer than an unfriendly walkback. I'll put that in.

**Comment by ericwinger** [comment]
I believe that add package checks for a default project now. Please let me know if there are other project operations that are missing the default check.
