### ISSUE TITLE
Jadeite/Rowan/3.2.15/SystemUser does not add methods to package (rowanCompile is `true)

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#64]
From the following screenshot:
![image](https://user-images.githubusercontent.com/623951/38751295-74773284-3f0c-11e8-9fae-a1b39241ce0e.png)
You should see that:
- `rowanCompile` is `true` (upper left workspace)
- a break point is set in RowanMethodService>>addOrUpdateMethod
- I have compiled the method GsFile class>>_stat:isLstat:

... and the method compile does not trigger the breakpoint in RowanMethodService>>addOrUpdateMethod and therefore the GsFile method is not added to the Rowan-3.4CompatFor3.2.15 package ... as it should.

I have tried both instance and class side methods, but the break point is not triggered and inspecting the loaded pacakge, it turns up empty:

![image](https://user-images.githubusercontent.com/623951/38751801-025835f2-3f0e-11e8-8061-c5241d212e42.png)

I have not tried any other combinations to see if they work or not ... I will fiddle around a little, because I was hoping to use JadeIte to do some re-packaging of methods

**Comment by dalehenrich** [comment]
Tried updating a method that was already in a Rowan package using the package tab in the browser and no joy:(

**Comment by dalehenrich** [comment]
After cloning Jade (pretty big download) and grepping through the Dolphin sources, I [found the spot where Jadeite is making reference to the global `rowanCompile`](https://github.com/ericwinger/Jade/blob/master/sources/Rowan%20UI%20Base.pax#L656-L663) ... and it is not using the RowanMethodService ... duh?

So I will dig a bit further ... and see what I can learn ... at least I am not hung up with nothing to do bu manually write the tonel file for the package:)

**Comment by dalehenrich** [comment]
set breakpoint in both of the `rwCompile*` methods in **Behavior** and still no joy...

**Comment by dalehenrich** [comment]
Despite the fact that `rowanCompile` evaluates to true in a SystemUser workspace:

![image](https://user-images.githubusercontent.com/623951/38753359-f23d28e4-3f12-11e8-80c0-4a868392835a.png)

The code is not taking the `ifTrue:` branch in the JadeServer64bit3x>>compileMethod... code ... which is a mystery to me at the moment.

The good news is that this does not look like a Jadeite bug ... although the possibility that this is a "Jade bug" still exists, since the `rowanCompile` global **is set in UserGlobals**:
![image](https://user-images.githubusercontent.com/623951/38753725-2e798f90-3f14-11e8-9d87-7d22eebc3826.png)

I am now suspicious that Jade inserts it's own `UserGlobals` symbol dictionary when it compiles **JadeServer64bit3x**, or ?????

**Comment by dalehenrich** [comment]
Disassembled the compiled method #compileMethod:behavior:symbolList:inCategory: and discovered that the UserGlobals that was compiled into the method (oop 11584001) is different that the UserGlobals accessible from the symbol list (oop 11583745):
```
topaz 1> disassem @48343553
JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory: (envId 0)
 method:48343553 sourceString:48401921 numArgs:4, public, literals at IP 192

Step/Source IP    Opcode         Description  (IP in bytes from &obj.hdr)
 ---/------ ---   -------------- -----------
  1/     1    56    create_VC_u1_forRfh_u2 u1=7 u2=1 
              64    copy_arg_s1_to_Vc_s2_temp_u3 s1=48 bytes s2=-16 bytes u3=2
              72    copy_arg_s1_to_Vc_s2_temp_u3 s1=40 bytes s2=-16 bytes u3=3
              80    copy_arg_s1_to_Vc_s2_temp_u3 s1=32 bytes s2=-16 bytes u3=4
              88    copy_arg_s1_to_Vc_s2_temp_u3 s1=24 bytes s2=-16 bytes u3=5
              96    copy_arg_s1_to_Vc_s2_temp_u3 s1=16 bytes s2=-16 bytes u3=6
             104    PUSH_SPECIAL_OOP_s s1=1300 val=Oop 1300 Class: UndefinedObject
             108    ALLOCTEMPS_u1 u1=1 
             112    CHKInt 
             114    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 23 Block oop 48632065 (MethodId 48401665 )) u2 = 94
             120    PUSH_LITERAL_oldGen_u1 u1=48 flag=0 zlitIdx:21 literal:Oop 18885377 aClass:  CompileWarning
             128    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 24 Block oop 48631809 (MethodId 48401409 )) u2 = 88
  2/   582   136    SEND sel=Symbol(oop 3176705) #'on:do:' env:0, 2 args, sendCache.u2=104 
             144    pop_n u1=1 
             152    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 25 Block oop 48631553 (MethodId 48401153 )) u2 = 72
             160    PUSH_LITERAL_oldGen_u1 u1=28 flag=0 zlitIdx:22 literal:Oop 130817 aClass:  Error
             168    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 26 Block oop 48631297 (MethodId 48400897 )) u2 = 64
  3/   752   176    SEND sel=Symbol(oop 3176705) #'on:do:' env:0, 2 args, sendCache.u2=96 
  4/   666   184    return_tos_u1 u1=48 bytes(6 words)

JadeServer64bit3x >> compileMethod:behavior:symbolList:inCategory:
 compileMethod: methodString behavior: aBehavior symbolList: aSymbolList inCategory: categorySymbol
	"returns (nil -> anArrayOfErrors) or (aGsNMethod -> compilerWarnings) or (aGsNMethod -> nil)"

	| method warnings | 

	[[(UserGlobals at: #rowanCompile ifAbsent:[false]) ifTrue:[
			method := aBehavior rwCompileMethod: methodString category: categorySymbol]
		ifFalse:[
			method := aBehavior
			compileMethod: methodString
			dictionaries: aSymbolList
			category: categorySymbol
			environmentId: environment].
	] on: CompileError do: [:ex |
		^nil -> (ex gsArguments at: 1)
	]] on: CompileWarning do: [:ex |
		warnings := ex gsArguments at: 1.
		ex resume.
	].
	^[	
		(self compiledMethodAt: method key selector inClass: aBehavior) -> warnings.
	] on: Error do: [:ex | 
		ex return: method -> warnings.
	].

topaz 1> disassem @48401665
 block for home method 48343553 
 method:48401665 sourceString:48401921 numArgs:0, public, literals at IP 104

Step/Source IP    Opcode         Description  (IP in bytes from &obj.hdr)
 ---/------ ---   -------------- -----------
  1/   220    56    PUSHVC_nArgsB_u1 u1=0 bytes(0 words)
              60    CHKInt 
              64    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 11 Block oop 49803777 (MethodId 48760577 )) u2 = 48
              72    PUSH_LITERAL_oldGen_u1 u1=20 flag=0 zlitIdx:10 literal:Oop 132097 aClass:  CompileError
              80    PUSH_CBLOCK_u2_VC_s1 s1=-16 (zlitIdx 12 Block oop 49803521 (MethodId 49787905 )) u2 = 40
  2/   517    88    SEND sel=Symbol(oop 3176705) #'on:do:' env:0, 2 args, sendCache.u2=40 
  3/   579    96    return_tos_u1 u1=16 bytes(2 words)

topaz 1> disassem @48760577
 block for home method 48343553 
 method:48760577 sourceString:48401921 numArgs:0, public, literals at IP 208

Step/Source IP    Opcode         Description  (IP in bytes from &obj.hdr)
 ---/------ ---   -------------- -----------
  1/   221    56    PUSHVC_nArgsB_u1 u1=0 bytes(0 words)
              60    CHKInt 
              64    push_literal_var_n n=144 zlitIdx:23 litVar.key:assocOop=11428353 key=UserGlobals 
              68    PUSH_LITERAL_oldGen_u1 u1=94 flag=0 zlitIdx:24 literal:Symbol(oop 34882305) #'rowanCompile'
              72    push_SBLOCK_u1 u1=152 (zlitIdx 25 Block oop 49769729 (MethodId 48292353 ))
  2/   235    80    SEND sel=Symbol(oop 3376129) #'at:ifAbsent:' env:0, 2 args, sendCache.u2=152 
  3/   271    88    pop_jump_if_false_topc_u24 u24=56 (jump to 144) topc=100 push_STK_s1_TEMP_u2
              96    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=4 
             104    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=3 
             112    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=6 
  4/   303   120    SEND sel=Symbol(oop 2713601) #'rwCompileMethod:category:' env:0, 2 args, sendCache.u2=144 
  5/   290   128    store_STK_s1_TEMP_u2 s1=-16 bytes, u2=7 
  6/   514   136    return_tos_u1 u1=16 bytes(2 words)
             144    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=4 
             152    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=3 
             160    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=5 
             168    push_STK_s1_TEMP_u2 s1=-16 bytes, u2=6 
             176    push_STK_s1_TEMP_u2_IV_u3 s1=-16 bytes u2=16 bytes u3=8
  7/   397   184    SEND sel=Symbol(oop 3264769) #'compileMethod:dictionaries:category:environmentId:' env:0, 4 args, sendCache.u2=112 
  8/   381   192    store_STK_s1_TEMP_u2 s1=-16 bytes, u2=7 
             200    return_tos_u1 u1=16 bytes(2 words)

[11428353 sz:2 cls: 111617 SymbolAssociation] a SymbolAssociation
  key                 [3962881 sz:11 cls: 110849 Symbol] UserGlobals
  value               [11584001 sz:14 cls: 111361 SymbolDictionary] a SymbolDictionary

[11584001 sz:14 cls: 111361 SymbolDictionary] a SymbolDictionary
  numElements         [50 sz:0 cls: 74241 SmallInteger] 6 == 0x6
  numCollisions       [18 sz:0 cls: 74241 SmallInteger] 2 == 0x2
  collisionLimit      [20002 sz:0 cls: 74241 SmallInteger] 2500 == 0x9c4
  tableSize           [42 sz:0 cls: 74241 SmallInteger] 5 == 0x5
  #1 [3962881 sz:11 cls: 110849 Symbol] UserGlobals
  #2 [11428353 sz:2 cls: 111617 SymbolAssociation] a SymbolAssociation
  #3 [20 sz:0 cls: 76289 UndefinedObject] nil
  #4 [39197185 sz:6 cls: 114177 IdentityCollisionBucket] a IdentityCollisionBucket
  #5 [20 sz:0 cls: 76289 UndefinedObject] nil
  #6 [20 sz:0 cls: 76289 UndefinedObject] nil
  #7 [20 sz:0 cls: 76289 UndefinedObject] nil
  #8 [32703233 sz:6 cls: 114177 IdentityCollisionBucket] a IdentityCollisionBucket
  #9 [12214785 sz:23 cls: 110849 Symbol] GsPackagePolicy_Current
  #10 [27387137 sz:2 cls: 111617 SymbolAssociation] a SymbolAssociation

topaz 1> send @11584001 keys
[50315521 sz:10 cls: 113921 SymbolSet] aSymbolSet
topaz 1> send @50315521 asArray
[50314753 sz:6 cls: 66817 Array] anArray
topaz 1> obj1 @50314753
[50314753 sz:6 cls: 66817 Array] a Array
  #1 [3962881 sz:11 cls: 110849 Symbol] UserGlobals
  #2 [5403649 sz:6 cls: 110849 Symbol] GcUser
  #3 [12214785 sz:23 cls: 110849 Symbol] GsPackagePolicy_Current
  #4 [14459137 sz:14 cls: 110849 Symbol] PackageLibrary
  #5 [26519809 sz:8 cls: 110849 Symbol] Nameless
  #6 [34935297 sz:25 cls: 110849 Symbol] RwGsLoadedProjectRegistry


topaz 1> send UserGlobals yourself
[11583745 sz:14 cls: 111361 SymbolDictionary] aSymbolDictionary

topaz 1> send @11583745 keys
[50312193 sz:15 cls: 113921 SymbolSet] aSymbolSet
topaz 1> send @50312193 asArray
[50311425 sz:11 cls: 66817 Array] anArray
topaz 1> obj1 @50311425
[50311425 sz:11 cls: 66817 Array] a Array
  #1 [3962881 sz:11 cls: 110849 Symbol] UserGlobals
  #2 [5403649 sz:6 cls: 110849 Symbol] GcUser
  #3 [12214785 sz:23 cls: 110849 Symbol] GsPackagePolicy_Current
  #4 [26519809 sz:8 cls: 110849 Symbol] Nameless
  #5 [34805761 sz:17 cls: 110849 Symbol] JadeServer64bit3x
  #6 [34806529 sz:17 cls: 110849 Symbol] JadeServer64bit24
  #7 [34807553 sz:15 cls: 110849 Symbol] JadeServer64bit
  #8 [34882305 sz:12 cls: 110849 Symbol] rowanCompile
  #9 [34928385 sz:10 cls: 110849 Symbol] JadeServer
  #10 [34928641 sz:17 cls: 110849 Symbol] JadeServer64bit32
  #11 [34935297 sz:25 cls: 110849 Symbol] RwGsLoadedProjectRegistry
```
So the upshot is that to access UserGlobals from the Jade methods that are compiled, you will need to do a lookup like `System myUserProfile objectNamed: 'UserGlobals'` (which would work in my image)....

....Unless I find something funky about the way I am compiling the Rowan methods when they are loaded by the script ... Stay tuned.

**Comment by dalehenrich** [comment]
Well I have not found the smoking gun related to how UserGlobals got changed ... also not quite sure how the Jade* classes end up showing up in the new UserGlobals ... I thought that all of those classes were completely hidden with normal Jade, so I am suspicious about some nefarious activity by Jadeite during login:) ... I've looked for references to UserGlobals in the Jadeite source repo and didn't find any .... also didn't find any gci login code either ...

**Comment by ericwinger** [comment]
Random thoughts for a long issue: 

- I haven't started breakpoints yet. You might consider using 'self halt'. That works for me.

- Jadeite still compiles the client code down to the server on login. I was waiting until we were developing "Rowan in Rowan" before I disabled that and started managing JadeServer code in Rowan. 

- >I am now suspicious that Jade inserts it's own UserGlobals symbol dictionary when it compiles JadeServer64bit3x, or ?????

I'm not sure if Jade is using it's own UserGlobals. I don't have an environment in front of me and can't remember exactly where the compile is being done. From memory, I think I just changed the JadeServer class compile code to say 'UserGlobals' in the dictionary argument. 

- Don't know if it is relevant, but there is closed issue #62 to consider. 

- Not sure if I understood your issue completely, but there may another compile path lurking in Jadeite which doesn't use the "#rowanCompile" global. 

Hope something here helps.

**Comment by dalehenrich** [comment]
breakpoints are working correctly ... the reason the breakpoint wasn't hit was that I set a breakpoint in the wrong method ...

I am in the process of trying to track down the point at which UserGlobals swtiches it's identity ... I'm still slogging through the process to see ... all I know is that by the time I resorted to disassembling the compiled method, the `UserGlobals` had lost it's identity ...

Issue #62 is not involved here ...

If you look at the debugger in [this comment](https://github.com/dalehenrich/Rowan/issues/64#issuecomment-381236051) you'll see that I hit the breakpoint in the method that references #rowanCompile global and that the non-Rowan branch was taken because #rowanGlobals is not in the UserGlobals symbol dictionary that was present when the method was compiled ...

So it's still at the point of trying to determine why the UserGlobals symbolDict was swtiched out ... at this point I have confirmed that the UserGlobals symbol dict that was present in the initial `extent0.dbf`is still present after the Rowan install script and Jadeite has done it's initial login ... but then I haven't gotten to the point where I've reproduced the original bug either ...

**Comment by dalehenrich** [comment]
The key information from the disassem analysis that I made [earlier](https://github.com/dalehenrich/Rowan/issues/64#issuecomment-381257729) is the following:

> Disassembled the compiled method #compileMethod:behavior:symbolList:inCategory: and discovered that the UserGlobals that was compiled into the method (oop 11584001) is different that the UserGlobals accessible from the symbol list (oop 11583745)

In other words the **JadeServer64bit3x>>compileMethod:behavior:symbolList:inCategory:**
 method was compiled referencing a UserGlobals symbol dictionary with an oop of 11584001, whereas the UserGlobals symbol dictionary that is available from the **SystemUser** symbol list has an oop of 11583745 ... **AND** I have found that the *mystery* UserGlobals in **JadeServer64bit3x>>compileMethod:behavior:symbolList:inCategory:** is from the DataCurator symbol list (**11584001**):
```topaz> set u DataCurator p swordfish
Warning: clearing the previous GemStone password.
topaz> login
[Info]: LNK client/gem GCI levels = 865/865
[Info]: User ID: DataCurator
[Info]: Repository: test_rowan2_dev_3215
[Info]: Session ID: 5
[Info]: GCI Client Host: <Linked>
[Info]: Page server PID: -1
[Info]: Login Time: 04/13/2018 20:29:00.565 PDT
Gave this VM preference for OOM killer, Wrote to /proc/25434/oom_score_adj value 250
[04/13/2018 20:29:00.569 PDT]
  gci login: currSession 1  linked session 
successful login
topaz 1> run
UserGlobals
%
[11584001 sz:14 cls: 111361 SymbolDictionary] aSymbolDictionary
```
and here is confirmation of the oop of the UserGlobals from SystemUser symbol list (**11583745**):
```
topaz> set u SystemUser p swordfish
Warning: clearing the previous GemStone password.
topaz> login
[Info]: LNK client/gem GCI levels = 865/865
[Info]: User ID: SystemUser
[Info]: Repository: test_rowan2_dev_3215
[Info]: Session ID: 5
[Info]: GCI Client Host: <Linked>
[Info]: Page server PID: -1
[Info]: Login Time: 04/13/2018 20:30:54.082 PDT
Gave this VM preference for OOM killer, Wrote to /proc/25434/oom_score_adj value 250
[04/13/2018 20:30:54.083 PDT]
  gci login: currSession 1  linked session 
successful login
topaz 1> run
UserGlobals
%
[11583745 sz:14 cls: 111361 SymbolDictionary] aSymbolDictionary
```

... So this is a Jade issue and we need to either:
- find the place where the DataCurator symbol list is used to compile the **JadeServer** methods
- or arrange to use `System myUserProfile objectNamed: 'UserGlobals'` in the Rowan code to pick up the correct UserGlobals.

**Comment by dalehenrich** [comment]
If it isn't clear (I didn't recognize what is going on when I reviewed this method the last time around), note that here is where the DataCurator symbol list is explicitly grabbed:
```Smalltalk
nextPutAll: 'symbolList := (AllUsers userWithId: ''DataCurator'') symbolList.'; lf;
```
and here is [where the DataCurator symbolList is used when methods are compiled](https://github.com/ericwinger/Jade/blob/master/sources/JadeServer.cls#L432-L435):
```smalltalk
	result := class
		compileMethod: source
		dictionaries: symbolList
		category: ''category''.
```

**Comment by dalehenrich** [comment]
and finally [here is the `blame` view of the code involved in using DataCurator's symbolList](https://github.com/ericwinger/Jade/blame/master/sources/JadeServer.cls#L456-L482). 

A number of different commits were involved in this area, but the significant commit appears to be [this commit](https://github.com/ericwinger/Jade/commit/cb9d3178d90567bbc69188643d21485fb43c78c7), when [the code to put the `DataCurator symbolList` into the compilation path for methods was introduced](https://github.com/ericwinger/Jade/blame/master/sources/JadeServer.cls#L468):
```Smalltalk
  nextPutAll: 'symbolList := (AllUsers userWithId: ''DataCurator'') symbolList.'; lf;
```

**Comment by dalehenrich** [comment]
Sooo, the easy fix for this will be to use `System myUserProfile objectNamed: 'UserGlobals'` when referencing the `rowanCompile` global ... The easy workaround is for me to arrange to set `rowanCompile` to true as DataCurator and then I will be able to move forward ...
