### ISSUE TITLE
Jadeite/Rowan/3.2.15/SystemUser ... looks like compile from within Jadeite debugger does not use Rowan API

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#66]
While working on getting a few tests to run, I ended up in a debugger and made a change to a method, but the method did not end up being added to the loaded things ...

Will verify that rowanCompile is properly set (earlier I was successfully adding methods to Rowan packages, so I'm pretty sure that this behavior is related to being in the debugger, but I need to verify that system browser is working)

**Comment by dalehenrich** [comment]
Confirmed that editing methods from browser do update the loaded things ... looks like the debugger must follow a different code path to compilation

**Comment by ericwinger** [comment]
Should be able to compile rowan methods in the debugger now.
