### ISSUE TITLE
Jadeite/Rowan/3.2.15/SystemUser ... get class history dialog when accepting a class creation template

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#68]
Here's the dialog that pops up when I accept a class change:
![image](https://user-images.githubusercontent.com/623951/38774022-b04809fe-4011-11e8-93c5-9ea5b0a5dcb0.png)
With Rowan it is not an option whether or not methods are copied to the new class and whether or not all subclasses (default checkboxes). The second two (unchecked) options instance migration and removing class from class history would be interesting options to include.

However, as it stands we need to disable/reroute this dialog to use Rowan api calls. for instance migration, the class RwGsInstanceMigrator implements Rowan migrations (use RwPrjLoadTool>>loadProjectNamed:withConfiguration:instanceMigrator: to specify the migrator instance... I haven't put any support in for whether or not the class history should be truncated, but it would be easy enough to do ...

**Comment by ericwinger** [comment]
Removed class creation dialog.
