### ISSUE TITLE
does not understand #isAddition

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#73]
When pressing Show Changes on the package menu in Jadeite, I was able to get past the "first" bug. However, then I encountered what looks to be a bug in the changes in Cypress to support McPatch. I'll include the stack: 

```
a MessageNotUnderstood occurred (error 2011), a CypressAddition does not understand  #'isAddition'
MessageNotUnderstood >> defaultAction @2 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @5 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
CypressAddition (Object) >> doesNotUnderstand: @9 line 10
CypressAddition (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
[] in  ExecBlock1 (JadeServer) >> _mcDescriptionOfPatch:baseName:alternateName: @2 line 12
OrderedCollection (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> _mcDescriptionOfPatch:baseName:alternateName: @17 line 11
JadeServer64bit32 (JadeServer) >> sbChangesInPackage: @10 line 9
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @65 line 22
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

```

**Comment by dalehenrich** [comment]
@ericwinger have you checked this code into Rowan or is it in a Jadeite.exe ... I am using the latest Jadeite.exe, but I still get the index 1 is out of bound (Issue #61).. when your code is available, I should be able to fix the bug pretty quickly (and test it:)

**Comment by dalehenrich** [comment]
@ericwinger ... the proposed patch is on my current `dale` branch (code was package with tODE ... and moved to Rowan-Cypress, now) ,,, but I should probably test it with your code first ... so bouncing back to you until you make your patches available

**Comment by ericwinger** [comment]
The fix for index out of bounds is still waiting to be merged into the master. Would like to work through that with you when you're in.

**Comment by dalehenrich** [comment]
Sounds good ... I have an HPI call at 9 and I'll head in afterwards ...

**Comment by dalehenrich** [comment]
I've merged your new master (459dd9c) into my branch and the walkbacks are gone, but I am not able to "see" the changes. I added the line `Transcript cr; show: 'hello'` and while the method does show up in the right text pane and there is a blank line in the left pane --- it is not obvious to me that there is a way to make the difference more visible:
![image](https://user-images.githubusercontent.com/623951/39007830-c4c8eaa8-43bb-11e8-8277-4329863020c4.png)

**Comment by ericwinger** [comment]
The timestamp in the diff seems to be hard coded: 
dkh 3/29/2018 14:21

(top of both source panes)

The value comes from an inst var, timestamp, in McMethodDefinition which is coming from somewhere. It is always the same. Any chance this is coming from Rowan? 

If these reflected the actual timestamps, that would help distinguish between the two versions.

**Comment by ericwinger** [comment]
Note - timestamps aren't used by Rowan so we need to remove that part of the view.

**Comment by ericwinger** [comment]
Removed timestamps and replaced with Disk: and Image: 

Package show changes now works and shows glyphs in the vertical bar (left of the text) where the differences are.

**Comment by ericwinger** [comment]
likely to be either a missing icons directory or a missing scilexer.dll in bin directory ..
