### ISSUE TITLE
Need better "Jadeite" branding

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#75]
Make all the "Jade" labels "Jadeite" (or something like that for Alpha)

**Comment by ericwinger** [comment]
Closing. Many changes made. Please re-open or add new issue if more branding is needed.

**Comment by LisaAlmarode** [comment]
Help > About Jade has some "Jade" version number.  Currently 2.1.18-41-g6180cf7.  
It's kind of important to be able to identify the version e.g. when reporting issues.   A mention of Alpha 1 useful but not sufficient; some increasing number, that can be tracked back to a particular version; perhaps a build date?  Would be useful.

**Comment by ericwinger** [comment]
Versioning done through git tag now. Jadeite displays it as well as the committish. 
https://github.com/ericwinger/Jade/commit/5decae389cea7cbf550d5ccb943642b134e06a03
