### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#8]
This may already have been discussed, but I am bringing up for a refresher. 

I think that the 'tools' references in Rowan should be hidden from the api. When I created a sample package, I ended up with code that looked like this: 

```
        | projectService |
        projectService := RowanProjectDefinitionService new.
        projectDefinition := projectService createSampleProject.
        self browserTool removePackageNamed: self samplePackageName.
        self projectTools load loadProjectDefinition: projectDefinition.
        projectDefinition addPackageNamed: self samplePackageName.

```

The successive calls to browserTool and projectTools are not intuitive.  

Perhaps we can discuss?

**Comment by dalehenrich** [comment]
I am very interested in this feedback ... when it appears:)

**Comment by ericwinger** [comment]
Yes, and expect much more now that I've got my grubby little paws all over your code. :)

**Comment by dalehenrich** [comment]
Well, this is somewhat related to Issue #7 ... I debated whether or not it was a good idea to introduce a project definition or not and as you point out, with a project definition in the mix, things get too confusing ...

There's quite a bit of complicated state that can be set in the project definition so I was trying to save myself from starting down the path of duplicating a bunch of methods but perhaps something like the following will give you access to projectDefinition while making sure that the definition is **loaded** after the edits are made --- which is the fundamental requirement when working with defintions:
```smalltalk
self browserTool 
  projectNamed: 'project name' 
  do: [:projectDefinition |
    ".... project definition operations"  ]
```
The implementation in browserTools would do the load after the block was executed, which is the pattern for all of the browserTool methods (so far) ... and an early return from the block would abort the operation.

**Comment by dalehenrich** [comment]
This model could be used to access definitions for all of the loaded things, if you find it convenient to fiddle with definitions ... if you look at the implementation of the methods in browserTools you'll see that there are some pretty strict rules in working with the definitions of loaded things ... since the defintions that are changed **have** to be derived from the original project definition that itself was derived from the loaded project ...

**Comment by ericwinger** [comment]
Let me have a looksie

**Comment by ericwinger** [comment]
Is there currently an equivalent method to #addClass:inPackageNamed:inProject: that uses the project name instead of the definition?

**Comment by dalehenrich** [comment]
`RwPrjBrowserTool>>createClass:inPackageNamed:` should do the trick ...

**Comment by dalehenrich** [comment]
@ericwinger and I agreed earlier today, to wait a bit before refactoring the browserTools/loadTools APIs ...
