### ISSUE TITLE
Remove "monticello username" from login dialog

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#80]
What the title says.
Also consider not defaulting to localhost - leaving it empty will prompt the user to fill it in.

**Comment by ericwinger** [comment]
Looks like Jade records the login information in the registry as suspected. If Jade has never been installed on a machine, my theory is that the login dialog will open up with a blank host. (or some sensible default). Thereafter, it will save your last login to the registry. 
Does this suffice? 

Here's the method for reference:
JadeLoginShell>>defaultPath

        | regKey appData |
        regKey := RegKey userRoot at: 'Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders' ifAbsent: [nil].
        appData := regKey valueAt: 'AppData'.
        (appData endsWith: ' Dat') ifTrue: [appData := appData , 'a'].          "Wine seems to cut off a character"
        ^appData , '\JadeDefaultConnection.gss'.
~

**Comment by ericwinger** [comment]
(oh, I'll have the Monticello name removed at the next .exe drop)
