### ISSUE TITLE
Delete extraneous files

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#81]
Jadeite's rowan.exe and the vast majority of the .dlls under /bin/ for old GS versions should be deleted.  On my windows box, norton deleted each old dll individually with its own dire warning, in a very visible and off-putting way.

**Comment by ericwinger** [comment]
rowan.exe was removed

**Comment by ericwinger** [comment]
dll's removed with 
https://github.com/ericwinger/Jade/commit/5decae389cea7cbf550d5ccb943642b134e06a03
