### ISSUE TITLE
Reloading brand new (no remote) project created by Jadeite 3.2PR7 

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#836]
This looks like a jadeite issue, but filing in Rowan per Dale's request.
Creating a brand new project without a remote origin repository should work, and does for a while, but removing and reloading it does not work. 

(1) create a project in Jadeite.
(2) add a package, class, and some methods.
(3) commit to git.  Repository on disk looks reasonable.
(4) unload.
(5) try to load this project back in using Jadeite. Get walkback, with error:

'performOnServer: ''set -e; cd /benton1/users/gsadmin/ROWAN37/myrowan/Isfahan; git --git-dir /benton1/users/gsadmin/ROWAN37/myrowan/Isfahan/.git --work-tree /benton1/users/gsadmin/ROWAN37/myrowan/Isfahan fetch origin'' stdout: ''fatal: ''''origin'''' does not appear to be a git repository?fatal: Could not read from remote repository.??Please make sure you have the correct access rights?and the repository exists.?'' failed with status: 32768 errno: 0 errStr: nil'

But there is no remote for this repository, which was just created from Jadeite out of the blue. 

I do see that installProjectFromFile: path projectsHome: projectsHomePath componentNames: componentNames resolveStrict: strict is using an argument of strict, which comes from Jadeite or anyway out of my stack visibility. 

![image](https://user-images.githubusercontent.com/13142166/178858020-0083f115-1d39-4085-bf87-5f6ccc26f00a.png)

**Comment by dalehenrich** [comment]
aha ... the resolveStrict: message is telling the load spec to unconditionally do a git checkout of the revision specified in the load spec if it is already on disk (with fetch being the first order of business) ... probably should throw an error when not dealing with a git-based repository ... good catch!

**Comment by LisaAlmarode** [comment]
Since I can load from the rowan command line, filed a jadeite bug, 935.

**Comment by dalehenrich** [comment]
GemTalk/Jadeite#935 fixed
