### ISSUE TITLE
REQUIRED: platform conditional required projects

### ISSUE THREAD

**Issue by rjsargent** [dalehenrich/Rowan#855]
This is probably(?) related to the issue "required projects use cases #705".

RwPlatformNestedProjectLoadComponentV2>>#projectNames says:
```
	"a platform nested component may only reference package names --- OR conditionals may only be used by a leaf node"

	^ #()
```

We need GS-specific components to be able to load GS-specific prerequisites.

**Comment by dalehenrich** [comment]
This issue only applies to the v2 implementation of components ... in v3 the restriction does not exist ... so I'll close this issue ...
