### ISSUE TITLE
UnPackaged project componentNames give errors when looked up by name

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#859]
My understanding is that the UnPackaged project is going away which may render this bug moot. But executing this in my image gives a walkback. Stack attached. 

```
| unpackagedProject |
unpackagedProject :=  RwProject newNamed: 'UnPackaged'. 
unpackagedProject componentNames collect:[:componentName | 
	unpackagedProject componentOrPackageGroupNamed: componentName]
```

[20220901_rowanServerStackDump_unpackaged_component_stack.txt](https://github.com/GemTalk/Rowan/files/9473416/20220901_rowanServerStackDump_unpackaged_component_stack.txt)

**Comment by ericwinger** [comment]
I'm going to retire this bug.  I now recall that before I got this error I tried to reload UnPackage project and got an error. Yet, I don't think I aborted and stopped the session (which I should have done) before continuing my work.  After logging out and back in, I no longer see the error. I think this is not really a "moot point" but a "red herring."  Or perhaps a "moot herring?"

**Comment by dalehenrich** [comment]
My money is on herring point ...
