### ISSUE TITLE
"STBFiler - input stream not in iSTB format" -- using latest jadeite.exe and latest Rowan source

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#86]
Not sure what's happening:
![image](https://user-images.githubusercontent.com/623951/39086516-66787486-4547-11e8-869d-7e554a4cdfcb.png)
There is a .stb file in the jadeite.directory:
![image](https://user-images.githubusercontent.com/623951/39086537-c2085b5e-4547-11e8-8783-1935de4c2330.png)
but it is older than the jadeite.exe and there doesn't seem to be a replacement copy in the distribution ...

I will try deleting the file (okay I will rename it) to see what happens, but if that won't work I am pretty much shut down and will have to see if an older .exe will work ...

If the file can be deleted safely, it might make sense to bullet proof the jadite.exe code from this particular error ...

**Comment by dalehenrich** [comment]
... oh the error pops up when I try to open a system browser using CTL-B...

**Comment by dalehenrich** [comment]
... renamed file and the browser now opens ...

**Comment by dalehenrich** [comment]
... i renamed the file, so if you want to look at it you can ...

**Comment by ericwinger** [comment]
I believe that this is a layout file for the system browser. It is created automatically when you close a browser. Presumably, it is used when a new browser is opened so you can retain state. 

I don't track that file in git and it isn't in the runtime directory on the Jadeite github project. 

It's possible you had an old one lying around from before I moved the .exe into git. And possibly, it had data that was stale or corrupted. The error displayed may be generic although I can't quickly pin down where it is coming from. 

If you still have the file, please attach it.

**Comment by dalehenrich** [comment]
... I deleted the file when I was having trouble with the Jadeite icons ... I guess we'll have to wait until it happens again ... wouldn't it be enough to ignore the stb error no matter the reason that it happens ... presumably this occurred after you had changed something in the systembrowser ... and any error should be treated as "ignore the layout and use the default layout"?

**Comment by dalehenrich** [comment]
Hit it again this morning ... attaching the stb file .. .txt is on the end to fool github
[Jade System Browser Layout.stb.txt](https://github.com/dalehenrich/Rowan/files/1947821/Jade.System.Browser.Layout.stb.txt)

**Comment by dalehenrich** [comment]
... the solution was to delete the file ... so it would be "better" if jadeite just ignored the error and pretended the file wasn't there in the first place ... or the error message should be change to tell user to delete the offending file ...
