### ISSUE TITLE
we might want a different color to indicate an "unloaded project" ...

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#87]
I understand that we haven't quite worked out what an "unloaded project", but showing the freshly cloned (but not loaded) project as red is somewhat concerning ... we _could_ not count a project as having version skew if the `loadedCommitId` is empty ... and at the moment an empty `loadedCommitId` is not a bad definition for "unloaded project".

I am working RowanSample1 and I see that the `*` shows up next to the project ... I thought that `*` indicated that the project was the default project, but I'm not so sure now, since I had to explicitly set the default project in the past ... 

Not sure whether or not this is an Alpa issue or not ... your call

**Comment by ericwinger** [comment]
The only thing I had to go on was (paraphrased) so I made any difference between the loaded sha and the disk sha show up as red. The * is the default project. 

I'll try to come up with a different scheme to distinguish between 
- unloaded projects
- default project
- skew

**Comment by LisaAlmarode** [comment]
I like the star for default (but we might want a footer with some help on that meaning).  And I like red for skew (assuming this means that "you've made changes that are uncommitted"). 

For a cloned but not-yet-loaded package... can we use italic?   We could pick another color, but really what you want is something that looks fainter.  I suppose a mid-gray color?

**Comment by LisaAlmarode** [comment]
Also... there's no indication when the user has made changes in the image, such that if they committed and pushed there would be a change written.  

While this is out of scope for alpha, we should at keep in mind the full set of colors or fonts so we don't need anyone to unlearn something (e.g. changing from red to green would be very challenging)

**Comment by dalehenrich** [comment]
au contraire, dirty state is on the table for the alpha - [I intend to fix the existing issues with dirty state for packages](https://github.com/dalehenrich/Rowan/issues/24#issuecomment-381301544) real soon now ... in fact I might just start work on this shortly:)

**Comment by dalehenrich** [comment]
... having it supported in Rowan means that dirty state indications can be added to Jadeite.exe when the time is right ...
