### ISSUE TITLE
Walkback with (possibly) misleading error message when saving a method in a hybrid category

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#873]
I added category `*rowansample9-tests` to class ` Rs9Interface` which is packaged in `RowanSample9-Core`. When I tried to save a method in that category, I got the following error:
```
 UserDefinedError occurred (error 2318), reason:halt, Attempt to add a method to an unpackaged class 'Rs9Interface', while using `hybrid-style` method protocol '*rowansample9-tests'
```
Since Rs9Interface is packaged, this is either an error or a misleading error message as it makes me think that Rs9Interface is unpackaged when clearly it is packaged. 

Stack attached. 

![image](https://user-images.githubusercontent.com/36212516/195697135-866f12b3-7066-4649-98a9-231047ffb9d4.png)

[20221013_rowanServerStackDump.txt](https://github.com/GemTalk/Rowan/files/9780256/20221013_rowanServerStackDump.txt)

**Comment by ericwinger** [comment]
Should note that Dale did comment on something related in a Jadeite bug - https://github.com/GemTalk/Jadeite/issues/921#issuecomment-1213613837

Not sure I quite understand what Jadeite could (should?) do.  Perhaps a discussion is in order as Dale suggested?

**Comment by dalehenrich** [comment]
@ericwinger, this looks like either spec_0061 or spec_0063 or ??? which one were you using?

**Comment by dalehenrich** [comment]
I just tried to reproduce the issue (using spec_0062) and discovered that the RowanSample9-Tests package wasn't loaded into my image for some reason it seems that only the dkh attribute was used during the load despite the fact that the 'tests' attribute is specified in the original load spec?

I also got a different error message ... but I'm also not using the latest Jadeite nor the latest RowanClientServices, so I'll need to do a fresh build before trying again ...

**Comment by ericwinger** [comment]
I'm using spec_0061 
![image](https://user-images.githubusercontent.com/36212516/195900950-99097b5b-378d-410b-b1c2-79a6ef99b966.png)

**Comment by dalehenrich** [comment]
Thanks ... I'll come back to this issue after I've done a new private build ...

**Comment by dalehenrich** [comment]
turns out that the project in this case is using Rowan package convention and and a category with a leading $* is not used for packaging .... I've inserted a Warning to this effect ...
