### ISSUE TITLE
(v2 & v3) tests that set currentPackage (in session temps) leave stale session temps state

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#881]
@AllenOtis had some failing GsFileIn tests that monkeyed with currentPackage and did not clear currentPackage after running tests which caused other tests to fail ... need to ensure that we clean up the session state before and after these tests ...

**Comment by AllenOtis** [comment]
DirectoryEntryTest
  #testCreationTimeIsADateAndTimeInstance (ms)
  #testModificationTimeIsADateAndTimeInstance (ms)

RwProjectFiletreeReaderWriterTest
  #testWriterReader_Rowan_pharo (ms)

FileReferenceTest
  #testUpToAll (ms)

RwSentButNotImplementedTest
  #testSentButNotImplemented (ms)

RwRowanProjectIssuesTest
  #testIssue208_move_method_from_project_to_project (ms)
  #testIssue310 (ms)
  #testIssue582 (ms)
  #testIssue72_addMethod (ms)
  #testIssue72_removeClass (ms)
  #testIssue72_removeClassWithExtensions (ms)
  #testIssue72_removeMethod (ms)
  #testIssue72_updateMethod (ms)

RwImplementedButNotSentTest
  #testImplementedButNotSent (ms)

RwRowanCrooked9Test
  #testIssue820 (ms)

FileHandleTest
  #testTruncate (ms)

RwHybridBrowserToolTest
  #testHybridMoveMethodFromSessionMethodsIntoSessionMethods (ms)
  #testHybridMoveMethodIntoSessionMethods (ms)

FileReferenceAttributeTests
  #testFileSize (ms)

ZnCharacterEncoderTests
  #testUTF8Back (ms)

RwProjectSetTest
  #testProjectAdoptTool (ms)
  #testProjectAdoptTool_existing_project (ms)

DiskFileSystemTest
  #testFileNames (ms)
Test
  #testIssue295_rename_package_move_newClassVersion_with_subclass_newProject (ms)
  #testIssue460_0 (ms)
  #testIssue514 (ms)
  #testIssue515_RowanSample2 (ms)
  #testIssue830_1 (ms)
  #testIssue830_2b (ms)
  #testIssue830_4b (ms)
  #testIssue830_5a (ms)
  #testIssue830_5c (ms)
  #testSpec_0023_1 (ms)
  #testSpec_0052_3 (ms)
  #testSpec_0059_1 (ms)
  #testSpec_0059_2 (ms)
  #testSpec_0082 (ms)

RwProjectToolTest
  #testProjectGlobalsClassesExtensionsInSessionMethods (ms)

RwBrowserToolApiTest
  #testClassCreationTemplate (ms)
  #testMoveGlobalExtensionSessionMethods (ms)
  #testNewClassVersionB (ms)
  #testNewClassVersion_session_method_change_extension_method_protocol (ms)
  #testNewClassVersion_session_method_change_extension_method_source (ms)
  #testNewClassVersion_session_method_unchanged_extension_method_protocol (ms)

RwProjectAuditToolTest
  #testAuditAndRepair_issue481_A (ms)
  #testAuditAndRepair_issue481_B (ms)
  #testAuditAndRepair_issue481_C (ms)
  #testAuditAndRepair_issue481_D (ms)
  #testMissingMethods (ms)
  #testNotification (ms)
  #test_Issue_535 (ms)

RwUnmanagedClassesV2Test
  #testCurrentTopazPackageFilein_03 (ms)
  #testCurrentTopazPackageMethod_01 (ms)
  #testMoveManagedMethod_01 (ms)
  #testMoveUnmanagedClass_01 (ms)
  #testMoveUnmanagedMethod_01 (ms)
  #testRemoveAllMethods (ms)
  #testUnmanagedClassNewVersion_01 (ms)
  #testUnmanagedClassNewVersion_02 (ms)
  #testUnmanagedClass_01 (ms)
  #testUnmanagedClass_02 (ms)
  #testUnmanagedClass_03 (ms)
  #testUnmanagedClass_04 (ms)
  #testUnmanagedClass_05 (ms)
  #testUnmanagedFilein_01 (ms)
  #testUnmanagedFilein_02 (ms)
  #testUnmanagedFilein_03 (ms)
  #testUnmanagedFilein_04 (ms)
  #testUnmanagedFilein_05 (ms)
  #testUnpackageManagedMethod_01 (ms)

RwGsTopazRowanToolTest
  #testTopazReadTonelFile (ms)
RwAdoptToolApiTest
  #testAdoptClassWithExistingExtensionMethods_1 (ms)
  #testAdoptClass_01 (ms)
  #testAdoptClass_02 (ms)
  #testAdoptMethod (ms)
  #testAdoptMethod_issue389_A (ms)
  #testAdoptMethod_issue389_B (ms)
  #testAdoptMethod_issue389_C (ms)
  #testAdoptMethod_issue389_D (ms)
  #testAdoptSymbolDictionary_1 (ms)
  #testAdoptSymbolDictionary_2 (ms)
  #testAdoptSymbolList_1 (ms)
  #testAdoptSymbolList_2 (ms)
  #testAdopt_issue481_A (ms)
  #testAdopt_issue481_A_F (ms)
  #testAdopt_issue481_B (ms)
  #testAdopt_issue481_C (ms)
  #testAdopt_issue481_D (ms)
  #testAdopt_issue481_E (ms)
  #testAdopt_issue481_F (ms)

RwPlatformPatternMatcherTest
  #testGemStoneVersionPattern (ms)

RwSymbolDictionaryTest
  #testClassAdditionPatch (ms)
  #testClassAdditionPatchWithCategory (ms)
  #testClassDeletionPatch (ms)
  #testClassPropertiesPatch (ms)
  #testClassVariableChangePatch (ms)
  #testClassVersioningPatch (ms)
  #testMethodAdditionPatch (ms)
  #testMethodDeletionPatch (ms)
  #testMethodExtensionPatchInSymbolDictionaryExtension (ms)
  #testMethodPropertiesPatch (ms)
  #testMethodSourcePatch (ms)

RwProjectTonelReaderWriterTest
  #testWriterReader_Rowan_pharo (ms)

RwTestProjectLibraryGeneratorTest
  #testLibraryGenerator (ms)
  #testRowanSample10LibraryGenerator (ms)

RwTopazTonelReaderTest
  #testCompileMethodsInFile (ms)
  #testCompileMethod_01 (ms)
  #testCompileMethod_02 (ms)
  #testCompileMethod_03 (ms)

RwProjectTopazReaderWriterTest
  #testWriterReader_A (ms)

RwUnpackagedBrowserApiTest
  #testAddUnpackagedClassMethod (ms)
  #testAddUnpackagedMethod (ms)
  #testIssue263 (ms)
  #testIssue420_A (ms)
  #testIssue420_B (ms)
  #testIssue420_C (ms)
  #testIssue420_D (ms)
  #testIssue420_E (ms)
  #testMoveUnpackagedMethod (ms)
  #testUpdateUnpackagedClassComment (ms)

RwUrlTest
  #testAsRwRepository (ms)
