### ISSUE TITLE
Possible loaded thing corruption for extension methods in classes that have changed shape

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/Rowan#91]
Working with fix for Issue #72, I found that I would get an error changing an extension method after the class has had it's class shape changed ... probably some things wrong with the book keeping while moving extension methods to new class versions ...

**Comment by dalehenrich** [comment]
In order to reproduce this issue, I created a Rowan test case: `RwRowanProjectIssuesTest>>testIssue01` where I've performed the following steps:
1. create class `issue91Class` in package 1.
2. add extension method `foo` in package 2.
3. add a new instance variable to `Issue01Class` and force a new version of the class to be created in package1.
4. change the extension method 'foo' in package 2.
Running this as a test does not produce an error. however, if these steps are followed in a Jadeite browser, the following stack shows up:

```
a UserDefinedError occurred (error 2318), reason:halt, Internal error -- no existing LoadedMethod found for the old compiledMethod.

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsSymbolDictionaryRegistry (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsSymbolDictionaryRegistry) >> addRecompiledMethod: @2 line 26
IdentityCollisionBucket (AbstractCollisionBucket) >> at:ifAbsent: @10 line 10
IdentityKeyValueDictionary >> at:ifAbsent: @15 line 13
RwGsSymbolDictionaryRegistry >> addRecompiledMethod: @14 line 23
RwGsMethodSourceSymbolDictPatch >> installSourcePatch @3 line 5
[] in  ExecBlock1 (RwGsPatchSetBasic) >> updateMethodDictionaries @2 line 10
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSetBasic >> updateMethodDictionaries @4 line 10
RwGsPatchSetBasic >> apply @20 line 25
RwGsTestImage class (RwGsImage class) >> applyModification:instanceMigrator: @10 line 9
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @13 line 13
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
[] in  ExecBlock2 (RwPrjBrowserTool) >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @41 line 55
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @23 line 85
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @12 line 37
Issue91Class class (Behavior) >> rwCompileMethod:category: @9 line 4
[] in  ExecBlock0 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @7 line 7
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
[] in  ExecBlock0 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @2 line 14
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @2 line 16
JadeServer64bit32 (JadeServer) >> sbSaveMethod: @12 line 9
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @121 line 40
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1
```
Sooo, at this point I am assuming that Jadelite may not be working with the proper version of the class ... cached **ClassOrganizer** or something else?

**Comment by ericwinger** [comment]
Hmmm ... Running the reproduction case doesn't produce the bug for me. 

One odd thing about your report. 
>add a new instance variable to Issue01Class and _**force**_ a new version of the class to be created in package1.

Two notes though:
1. What do you mean by "force..."? The only way to add the inst var sets the package to package1 by default.
2. Interestingly in step 3 of the issue report, if I create the new version of the class in package 2 (where the extension method lives), Rowan moves the class definition to package 2. However, it loses my method. 

Reassigning to @dalehenrich for possible bug in bullet 2.

**Comment by ericwinger** [comment]
> You say that the "Running the reproduction case doesn't produce the bug for me." ... did you execute smalltalk code or do the steps in the browser?

Missed that. I did this in a browser.

**Comment by dalehenrich** [comment]
Using Jadeite [Alpha1.0] and the latest on dale branch (983f3af) with number of bugfixes in this area and was not able to reproduce my original bug report ... I did my test using the `packages` tab ... I will make another run at this using the `dictionaries` tab.

**Comment by dalehenrich** [comment]
works with `dictionaries` tab ... calling this fixed

**Comment by dalehenrich** [comment]
RwHybridBrowserToolTest>>testHybridMoveMethod reproduces the original failure. Reopening

**Comment by dalehenrich** [comment]
wrong bug
