### ISSUE TITLE
RwGitTool>>gitcheckoutIn:with: does not create a git command

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#910]
Sending `RwGitTool>>gitcheckoutIn:with:` with the following arguments creates the commands below.  It doesn't look like a valid git command. Stack dump attached. 

_gitRootReference:_ `FileReference disk @ '/uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1'`
_args:_ 'temp'

```
'set -e; cd /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1; git --git-dir /uffda1
/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1/.git --work-tree /uffda1/users
/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1 checkout temp'
```
I get this error when run from a command line: `No such file or directory`
```
ewinger@uffda:/uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1$ 'set -e; cd /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1; git --git-dir /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1/.git --work-tree /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1 checkout temp'
bash: set -e; cd /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1; git --git-dir /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1/.git --work-tree /uffda1/users/ewinger/rowanStones/checkouts/gemstone37rowanv3_externals_st/RowanSample1 checkout temp: No such file or directory
```
[2024-01-12_172860327_rowanServerStackDump.txt](https://github.com/GemTalk/Rowan/files/13923192/2024-01-12_172860327_rowanServerStackDump.txt)

**Comment by dalehenrich** [comment]
Well the error from the command line version of the command is because you've got a leading and trailing $', so bash is trying to execute that as an executable command ... remove those and you'll get a better result ...

**Comment by dalehenrich** [comment]
What error were you getting when you ran the command from within the image? In the stack, you are stopping at a breakpoint ... so no Smalltalk error information ...

**Comment by ericwinger** [comment]
```
Well the error from the command line version of the command is because you've got a leading and trailing $', 
```
Yup, you're right.  No error in the command. Something else is going on.
