### ISSUE TITLE
Need to discuss getting started with Rowan post-Alpha

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#92]
The project menu options in alpha are not general enough for a product. We need to discuss how a customer will get started with Rowan and build Jadeite functionality to match. 

Assigning to Dale for initial thoughts. 

Post alpha.

**Comment by dalehenrich** [comment]
@ericwinger Is this still a relevant issue?

**Comment by ericwinger** [comment]
Think we're past this.
