### ISSUE TITLE
Need About Jadeite text

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#95]
Need some text to describe the Jadeite product. Lisa, can you help? 

Jadetite Login window>Help>About Jade.

**Comment by LisaAlmarode** [comment]
I don't know that we need actual description.  What we need is some version so customer (me) can determine if what I have is the latest or not.  E.g.
    Version: Alpha 1 of May 23, 2018.

If we want description, something like this:
     Jadeite is an open-source Smalltalk GUI IDE for use with Rowan-enabled 
     GemStone, developed by GemTalk Systems LLC.  

It would be nice to have url of the git project but that's still in the future.  Could leave off the "open-source".

**Comment by ericwinger** [comment]
Consolidated the two About Jade menu options into one which shows the git tag and url now. Jadeite tag currently set to 0.9.0.
