### ISSUE TITLE
Nits

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#98]
My $ROWAN_HOME directory gets files cypress.out, rowan.out, ston.out and tonel.ot.  The missing  "u" in that last one, sets my teeth on edge every time...

The Project List Browser window title is "Rowan Project List Shell".  The Rowan is iffy... but the "Shell" certainly should be "Browser".

The login dialog title is "Untitled-Jadeite Login".  That "Untitled" doesn't look good.

While these aren't functional issues, if they are not too intrusive it would be nice to fix.

**Comment by dalehenrich** [comment]
my patch will available on my next merge into master ...
